### ISSUE TITLE
[FR] Show latest/all available package versions

### ISSUE THREAD

**Issue by fonsp** [pikapkg/cdn#100]
Awesome project, very exciting!

Small request: On the landing page of a package ([example](https://www.skypack.dev/view/leftpad)), it is currently not possible to see its latest version, (or the list of available versions).

**Comment by drwpow** [comment]
Thanks for your question. We are actually working on this, and will hopefully announce this feature soon! And you’ll be able to browse a bit more than just what versions are available 😉

**Comment by drwpow** [comment]
Update: we’re still working on an improvement on this, but just to give you a little sneak peak of what‘s in beta: https://www.skypack.dev/view/preact/browse (just add `/browse` to the end of any package url). You can not only see all versions of a package, but you can also browse all files for that version (as uploaded to npm).

Keep in mind that this is still experimental—we’d like to improve on this a bit more. Currently you can browse the contents of what gets loaded to _npm_, but you can’t see a version of the package that Skypack optimizes for production.

Anyway, thanks again for the suggestion! We’ll release more info on this soon 🙂

**Comment by CanRau** [comment]
Would be fantastic if I could select a specific version an be presented with a cdn.skypack link 😍

**Comment by CanRau** [comment]
Would be fantastic if I could select a specific version an be presented with a cdn.skypack link 😍
