### ISSUE TITLE
[Package issue] @urql/preact

### ISSUE THREAD

**Issue by zachasme** [pikapkg/cdn#102]
Importing @urql/preact does not work:

```ts
import("https://cdn.skypack.dev/@urql/preact");
```

It leads to `https://cdn.skypack.dev/-/preact@v10.5.9-WjJBSHNrNEdRNYTaCveQ/dist=es2020/preact/hooks` being requested (missing .js extension).

I assume it is imports such as [this import in useMutation.ts](https://github.com/FormidableLabs/urql/blob/8224ed0c5dbc31d62102254d50d9c1584c84c601/packages/preact-urql/src/hooks/useMutation.ts#L2) which imports from `
preact/hooks` being translated into the above.

**Comment by drwpow** [comment]
Thanks for raising! `/preact/hooks` should technically be the correct import (no extension), as that’s what is specified in preact’s `package.json` `"exports"`. It’s a bug on our end that we require the `.js` extension there.

We’re currently working on a fix to the CDN that should hopefully resolve this soon.

**Comment by drwpow** [comment]
Update: a recent release to the CDN has fixed this! 🎉 You should be able to use `@urql/preact` now. If you encounter any issues, please don’t hesitate to reopen this ticket, or open a new issue if you run into something else.
