### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'property' of '__commonjs_module0' as it is null.

### ISSUE THREAD

**Issue by coryrylan** [pikapkg/cdn#105]
One of our newer package versions runs into the following error when using this import

```js
import 'https://cdn.skypack.dev/@cds/core@v5.0.0-rc.0/button/register.js';
```

```js
property.js:2 Uncaught TypeError: Cannot destructure property 'property' of '__commonjs_module0' as it is null.
```

```js
import __commonjs_module0 from "/-/lit-element@v2.4.0-IskkdiSLGcK46AGbST1n/dist=es2020/lit-element.js";
const {property: prop} = __commonjs_module0; // exception
```

The file is located here: https://cdn.skypack.dev/-/@cds/core@v5.0.0-rc.0-I8JkLqtDNXzuuelPzFZc/dist=es2020,mode=raw/internal/decorators/property.js 

It looks like the import as syntax might be tripping it up. In the previous version (`5.0.0-next.0`) of this package that same import line existed but did not seem to cause any issue. Looks like this might be related to https://github.com/snowpackjs/skypack-cdn/issues/64 and https://github.com/snowpackjs/skypack-cdn/issues/35

**Comment by sastan** [comment]
I found the same error using style-vendorizer with twind:

https://cdn.skypack.dev/-/twind@v0.11.2-7t5YkoLCJSmzbznJ6qKv/dist=es2020/twind.js

```js
import __commonjs_module0 from "/-/style-vendorizer@v2.0.0-M3RNjjqClSTio1f91tNw/dist=es2020/style-vendorizer.js";
const {cssPropertyAlias} = __commonjs_module0;
const {cssPropertyPrefixFlags} = __commonjs_module0;
const {cssValuePrefixFlags} = __commonjs_module0;
```

style-vendorizer has esm modules:

- https://www.skypack.dev/view/style-vendorizer
- https://cdn.skypack.dev/-/style-vendorizer@v2.0.0-M3RNjjqClSTio1f91tNw/dist=es2020/style-vendorizer.js

**Comment by matthewp** [comment]
Thanks for reporting. I see that we have some false positives in our CJS dependency detection. I have an idea of the issue and am looking to fix.

**Comment by matthewp** [comment]
Verified a fix in our staging environment, awaiting approval to fix in production.

**Comment by coryrylan** [comment]
Thank you for the quick response!

**Comment by FredKSchott** [comment]
Fixed and deployed to production. Sorry for the disruption everyone!

**Comment by netgfx** [comment]
having the same issue for `https://cdn.skypack.dev/@react-three/drei`
```
warn: [modules-runtime] Error in './Target.jsx': TypeError: Cannot destructure property 'CharsetEncoder' of '__commonjs_module0' as it is null.
    at https://cdn.skypack.dev/-/three-stdlib@v2.6.2-IJ75zJqcawqMqsNMUllo/dist=es2019,mode=imports/optimized/three-stdlib.js:5:8
```
