### ISSUE TITLE
Trying to import a package with node internals gives a useless 500 error.

### ISSUE THREAD

**Issue by Yamboy1** [pikapkg/cdn#11]
when you try and import from a package that depends on node internals, say `https://cdn.pika.dev/-/mkdirp@v1.0.4/dist=es2019/mkdirp.js`, the cdn gives a relatively useless 500 error: `Build Error: This package could not be built.`. The only reason that i understand this error was because i was testing out what pika would do in this case. The output from deno is also just as nondescript, but i'm not sure what can be done on your side about that 😅.
```
~/deno-testing 
❯ deno cache mkdirp.ts
Download https://cdn.pika.dev/mkdirp
Download https://cdn.pika.dev/-/mkdirp@v1.0.4/dist=es2019/mkdirp.js
error: Import 'https://cdn.pika.dev/-/mkdirp@v1.0.4/dist=es2019/mkdirp.js' failed: 500 Internal Server Error
```

**Comment by FredKSchott** [comment]
The current plan is to actually allow these moving forward, and then let the browser/deno fail on it instead. That should give you a better error message in both environments, and then would allow us to start polyfilling them based on your environment (deno has a node fs polyfill, for example, that we could import from instead).

**Comment by FredKSchott** [comment]
Fixed!
