### ISSUE TITLE
Importing Three.js & a Three.js control importing Three.js causes a double import of Three.js

### ISSUE THREAD

**Issue by backspaces** [pikapkg/cdn#112]
These two imports:
```
import * as THREE from 'https://cdn.skypack.dev/three@0.120.0'
import { OrbitControls } from 'https://cdn.skypack.dev/three@0.120.0/examples/jsm/controls/OrbitControls.js'
```
.. results in a double import of Three. This is due to OrbitControls importing Three via: ../../../build/three.module.js

There is an issue on Three's github repo. Here is my reply with detailed description of skypack use and a solution that I used when using npm (which skypack makes unnecessary!).
https://github.com/mrdoob/three.js/issues/17482#issuecomment-761883874

Although this is labeled with Three.js, I believe this may occur in any repo with relative links used in imports.

**Comment by matthewp** [comment]
ah, so you're getting 2 different files, but they are both the "three" code.  It's not that they are relative links, but that they are pointing to different files, I believe.

**Comment by backspaces** [comment]
I think you're right. I posted this solution on the three.js site:
https://github.com/mrdoob/three.js/issues/17482#issuecomment-762459506
.. which makes sure both refer to the same Three.

Here's the text:

This possibly solves the problem: rather than the default Three.js, specifically import the same module as OrbitControls uses:
```
import * as THREE from 'https://cdn.skypack.dev/three@0.120.0/build/three.module.js'
import { OrbitControls } from 'https://cdn.skypack.dev/three@0.120.0/examples/jsm/controls/OrbitControls.js'
```

I presume that is similar to what the rest of us are doing? I.e. the equivalent of:
```
import * as THREE from '../node_modules/three/build/three.module.js'
import { OrbitControls } from '../node_modules/three/examples/jsm/controls/OrbitControls.js'
```

**Comment by drwpow** [comment]
> This possibly solves the problem: rather than the default Three.js, specifically import the same module as OrbitControls uses:

Yes that will provide a workaround short-term. But we‘d like to provide better resolution for this on Skypack’s end. Looking into a better fix long-term to see if we can prevent the duplicate import.

**Comment by trusktr** [comment]
Last time I checked skypack uses rollup to bundle entrypoints, and as long as it does that it will always have the duplicate modules problem (in some cases).

I think skypack would need to abandon its bundling approach in order to solve the issue. A theoretical pure-ESM server would serve every file individually, and not create bundles (with possible duplicates across bundles).

**Comment by drwpow** [comment]
Update: it looks like @matthewp has fixed this issue! 🎉. Now when you import Three and examples, you should no longer see it downloading twice. I’m going to mark this issue as resolved, but please feel free to comment or re-open if you’ve found another issue where this isn‘t the case.

**Comment by mrdoob** [comment]
I think you guys will like to know that we're working on solving this on our end: https://github.com/mrdoob/three.js/pull/21654
