### ISSUE TITLE
Can not find @fluentui/react

### ISSUE THREAD

**Issue by bobby-alain** [pikapkg/cdn#114]
Can not find @fluentui/react

**Comment by rizrmd** [comment]
did you find the solution ?

**Comment by drwpow** [comment]
I’m seeing `@fluentui/react` both on https://www.skypack.dev/view/@fluentui/react and https://cdn.skypack.dev/@fluentui/react. Happy to look into any issues if I get more context, but I’m not sure what the issue is here.
