### ISSUE TITLE
[Package Error] "monaco-editor@v0.21.3" could not be built.

### ISSUE THREAD

**Issue by berkant** [pikapkg/cdn#115]
Here's the link: https://cdn.skypack.dev/error/build:monaco-editor@v0.21.3-Haql2pvlzICZEAu7qERZ

```javascript
/*
 * [Package Error] "monaco-editor@v0.21.3" could not be built. 
 *
 * No build output found.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/pikapkg/cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://pika.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"monaco-editor@v0.21.3\" could not be built. ");
throw new Error("[Package Error] \"monaco-editor@v0.21.3\" could not be built. ");
export default null;
```

**Comment by matthewp** [comment]
Hi, thanks for reaching out. I believe what is happening here is that it runs out of memory. I'll try to load this and see what the logs are saying. We definitely want to try and get Monaco working.

**Comment by berkant** [comment]
Any updates?

**Comment by matthewp** [comment]
Not yet, I'm going to look into this this week.

**Comment by matthewp** [comment]
Hey @0xbkt, I checked and this package is building in our staging environment. We plan to do a release this week which includes build fixes, I expect that will fix the package in prod. I'll let you know when that has been done.

**Comment by berkant** [comment]
@matthewp Guess the package is now in CDN. If you confirm please close the issue.
