### ISSUE TITLE
Code is being transformed incorrectly

### ISSUE THREAD

**Issue by nksaraf** [pikapkg/cdn#12]
I was working on a package called https://github.com/nksaraf/use-monaco and trying to use it from the Pika CDN. But one of the files (I am using the exports map feature), had a small transform done to the code that made it incorrect and it gave me this error at the spot of `_singleSlashStart` in line 1706 on the image. Some of the regex is being stripped.
Link to pika cdn:
https://cdn.pika.dev/-/use-monaco@v0.0.2-patch.1-6dh6OWhfr1PFcUiczNmz/dist=es2019,mode=exports/worker

Link to unpkg (correct version):
https://unpkg.com/use-monaco@0.0.2-patch.1/dist/esm/worker.js

<img width="444" alt="Screen Shot 2020-05-30 at 2 13 49 AM" src="https://user-images.githubusercontent.com/11255148/83321071-112cbb80-a202-11ea-844a-56028263dc4c.png">

<img width="1120" alt="Screen Shot 2020-05-30 at 2 12 52 AM" src="https://user-images.githubusercontent.com/11255148/83321050-ef333900-a201-11ea-9d51-e75d7eaa87c0.png">

**Comment by nksaraf** [comment]
Appears to be stripping as a comment.

**Comment by FredKSchott** [comment]
Thanks for filing, I bet that's it. I'll take a look this weekend, should hopefully be a quick fix.

**Comment by nksaraf** [comment]
> Thanks for filing, I bet that's it. I'll take a look this weekend, should hopefully be a quick fix.

Hi Fred, any updates on this? Sorry for bothering.

**Comment by FredKSchott** [comment]
Fixed! Thanks for your patience.

Note: deep imports (a file within a package that isn't the main package entrypoint) are still experimental. Should be more supported by the end of the month.
