### ISSUE TITLE
How to use skypack in intranet?

### ISSUE THREAD

**Issue by rainmanhhh** [pikapkg/cdn#122]
some of my apps are running in intranet, so directly import from cdn.skypack.dev is not available in production env. 
is it possible to download a esm lib(such as react) as single file js?

**Comment by drwpow** [comment]
Hey @rainmanhhh! It sounds like [esinstall](https://github.com/snowpackjs/snowpack/tree/main/esinstall) is probably what you’re looking for—that handles the single-file ESM builds.

You might also be familiar with [Snowpack](https://github.com/snowpackjs/snowpack) too, which uses esinstall at its core but also features a dev server and build optimizations. Hope this helps!
