### ISSUE TITLE
Some useful headers are hidden by CORS

### ISSUE THREAD

**Issue by KallynGowdy** [pikapkg/cdn#124]
Hi! While using Skypack I noticed that some headers are being blocked by CORS.
In addition to the regular ones, it seems like the `x-typescript-types`, `x-import-url`, and `x-pinned-url` headers are not allowed when requesting a module in a web browser.

Is it possible to whitelist these headers by including a `Access-Control-Expose-Headers` header in the response?

**Comment by drwpow** [comment]
Thanks for the heads up! I am seeing those headers in Firefox on a normal url (e.g. `https://cdn.skypack.dev/react`). Please note that not all headers appear on a pinned URL (e.g. `https://cdn.skypack.dev/pin/…` only sends `x-import-url`, I believe). Are you able to provide your full request headers, along with the browser you’re using?

**Comment by KallynGowdy** [comment]
Here is a repro: [https://codesandbox.io/s/flamboyant-meadow-sm2i8?file=/src/index.js:271-304](https://codesandbox.io/s/flamboyant-meadow-sm2i8?file=/src/index.js:271-304)

Basically it just requests the module (by normal url) using an XHR/fetch request.
From what I can tell, the headers are being sent to the web browser - but due to a [security feature](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header) browsers do not pass all the headers to the JavaScript app. Instead, only the safelisted ones are sent by default.

Luckily, the [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) header can be used to explicitly tell the web browser which additional headers should be given to the JS app.

In the repro above the headers that are available to the app are:
```json
{
  "cache-control": "private, max-age=300",
  "content-type": "application/javascript; charset=utf-8"
}
```
even though there are all sorts of other headers included:
```
date: Fri, 05 Feb 2021 04:22:03 GMT
content-type: application/javascript; charset=utf-8
set-cookie: __cfduid=xxxx; expires=Sun, 07-Mar-21 04:22:03 GMT; path=/; domain=.skypack.dev; HttpOnly; SameSite=Lax
access-control-allow-origin: *
x-typescript-types: /-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=types/index.d.ts
cache-control: private, max-age=300
x-import-url: /-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020/react.js
x-pinned-url: /pin/react@v17.0.1-tOtrZxBRexARODgO0jli/react.js
...
```

After including something like this in the response headers:
```
Access-Control-Expose-Headers: x-typescript-types, x-import-url, x-pinned-url
```

I would expect the available headers to start reporting this:
```json
{
  "cache-control": "private, max-age=300",
  "content-type": "application/javascript; charset=utf-8",
  "x-typescript-types": "/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=types/index.d.ts",
  "x-import-url": "/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020/react.js",
  "x-pinned-url": "/pin/react@v17.0.1-tOtrZxBRexARODgO0jli/react.js"
}
```

For reference, here is the request:
```
GET /react?dts HTTP/2
Host: cdn.skypack.dev
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: https://sm2i8.csb.app
Referer: https://sm2i8.csb.app/
Connection: keep-alive
```

And I am testing with Firefox (v84).

I also noticed that if my browser had the module cached it may not include the headers I was looking for (because they were not included in the cached response) so for this test I disabled caching to make sure the headers showed up.

Thanks!

**Comment by drwpow** [comment]
Ah thank you for the reproduction! Sorry—I did not think about XHR requests. I see what you mean now. Yes we should be able to expose those headers no problem. Thanks for the suggestion! Will update you once these are available.
