### ISSUE TITLE
[deno][snowpack] Running esinstall...  Failed to load node_modules/skypack/lib/index.js

### ISSUE THREAD

**Issue by harleylang** [pikapkg/cdn#128]
I was experimenting with a dev environment that combined deno and snowpack. I started with:

```
deno run https://cdn.skypack.dev/snowpack
```

And encountered the following error:

```
 * [Package Error] "snowpack@v3.0.11" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Failed to load node_modules/skypack/lib/index.js
 *     Assigning to rvalue (132294:8) in skypack/lib/index.js
 *   Install failed.
 *   Install failed.
```

Error url: 
https://cdn.skypack.dev/error/build:snowpack@v3.0.11-CJVnruRToA4n4Kfas4WS

**Comment by FredKSchott** [comment]
Snowpack is a Node.js based tool, and isn't designed to run via Deno (it would be great if it could, though!).

That error message could be better though, I'm not quite sure what "assigning to rvalue" means

**Comment by harleylang** [comment]
Thanks @FredKSchott for confirming! I'll close given that this experimental setup is not possible.
