### ISSUE TITLE
react-icons - Error: Cannot find module 'react-icons/fi' or its corresponding type declarations

### ISSUE THREAD

**Issue by Nipodemos** [pikapkg/cdn#129]
Hello again!

When importing an icon from the react icons package while using skypack, I get an error that the package was not found.

### App.tsx file:
```tsx
import React from 'react';
import { FiLogIn } from 'react-icons/fi';

interface AppProps {}

function App({}: AppProps) {
  return (
    <h1>
      Hello World
      <FiLogIn/>
    </h1>
  );
}

export default App;
```

### Commands to reproduce the issue:
```bash
npx create-snowpack-app test-react-icons-skypack --template @snowpack/app-template-react-typescript
cd test-react-icons-skypack
npm start
```

### screenshots:
![image](https://user-images.githubusercontent.com/11494727/107131309-fa238a80-68b3-11eb-8cef-8bdef61784e2.png)
![image](https://user-images.githubusercontent.com/11494727/107131357-47076100-68b4-11eb-8bf7-1cd9a0146a17.png)

### Something worth mentioning
* When I start the project using `npm start`, it runs normally, but because of this error, the file does not updates on change, so I need to restart everything for it to update
* Installing locally react-icons by using `npm install react-icons` makes everything works just fine, even with the skypack still enabled

**Comment by matthewp** [comment]
Thanks! I'll try out this import and see what is going on.

**Comment by matthewp** [comment]
This seems to work fine in Skypack: https://cdn.skypack.dev/react-icons/fi loads correctly. I'll talk with others to see if there's anything different about Snowpack's streaming imports that would cause this.

**Comment by Nipodemos** [comment]
The weird thing is that it does works, the code compiles and the icon is show. However, because of the error detected, skypack won't refresh the page, so changes that I make will not be reflected. But if I stop snowpack server and run it again, it will get the updated content working.
So as you mentioned it may be more a snowpack problem than skypack

I'll create an issue there and see if they know anything that can help

**Comment by Nipodemos** [comment]
I've discovered the problem. Seems like I needed to install the types of the react-icons package 😅 
Typescript helps but sometimes is a pain.

Sorry for bother you guys, it was my fault.

Thanks for the excelent work!

**Comment by Nipodemos** [comment]
Well... this is embarassing, but the problem persists. The error is gone, but the snowpack server is not updating on save, but i gues now this is a snowpack problem. I'll create an issue there

https://github.com/snowpackjs/snowpack/discussions/2585
