### ISSUE TITLE
HTTP Caching for top-level URL?

### ISSUE THREAD

**Issue by vinsonchuong** [pikapkg/cdn#13]
Hi, first time user here. Thanks for the great work! Who would have thought that replacing a bunch of build tooling with no tooling could have such an impact!

I noticed that with the following line:

```
import React from 'https://cdn.pika.dev/react@^16.13.1
```

It always re-validates that URL along with those of its three imports before getting 304's and using the cache.

So, I had the idea of just importing a specific version, without the `^`. My thinking is that a fixed version of a package should be cacheable in the browser indefinitely. Is there a reason this doesn't currently happen?

Thanks!

**Comment by FredKSchott** [comment]
Yup, there are a couple of reasons for this, a blog is coming soon that will outline.

But, there's another way to get the performance you're seeking:

```
import React from 'https://cdn.pika.dev/pin/react@v16.13.1-ByypZEPVPs6cpkpGdpQK/dist=es2019/react.js';
```

Documentation for this is also still in progress, but this is essentially the cache-friendly way to do of a `/react@16.13.1` lookup. I got that URL from original response, but replaced `/-/react...` with `/pin/...`. You can do this for any package on the CDN.
