### ISSUE TITLE
[Package Error] "antd@v4.12.2" could not be built. 

### ISSUE THREAD

**Issue by wlc534** [pikapkg/cdn#130]
[https://cdn.skypack.dev/error/build:antd@v4.12.2-o1WNNmlSl9kaOSybE9FP](url)
/*
 * [Package Error] "antd@v4.12.2" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Could not resolve "@ant-design/icons/es/components/Context".
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"antd@v4.12.2\" could not be built. \n[1/5] Verifying package is valid…\n[2/5] Installing dependencies from npm…\n[3/5] Building package using esinstall…\nRunning esinstall...\nCould not resolve \"@ant-design/icons/es/components/Context\".");
throw new Error("[Package Error] \"antd@v4.12.2\" could not be built. ");
export default null;

**Comment by matthewp** [comment]
Thanks! We've been having an issue with antd for a little while now. I'm going to take a look this week and see if I can figure out what the issue is.

**Comment by matthewp** [comment]
antd is working again: https://cdn.skypack.dev/antd

Thanks for reporting (and your patience)!

**Comment by donald-richardson-dxd** [comment]
Issue appears to be back.

**Comment by YourTechBud** [comment]
The issue seems to be back
