### ISSUE TITLE
Pinned Minified URL's are broken

### ISSUE THREAD

**Issue by mbrandt-art** [pikapkg/cdn#131]
Following the import chain (pinned, minified) for `dset`: 
- https://cdn.skypack.dev/dset
  - looks fine
- https://cdn.skypack.dev/pin/dset@v3.0.0-FxiY6gwKR0msQDjwfbYd/mode=imports,min/dset.js
  - looks fine
- https://cdn.skypack.dev/-/dset@v3.0.0-FxiY6gwKR0msQDjwfbYd/dist=es2020,mode=imports,min/dset.js
  - "The source is unknown"

Following the chain was working fine the past few days (just noticed the error this morning). I tried the same chain for `hueman` and `dotz` to find the same issue. Seems like it's not a package-specific issue

**Comment by vimbrandt** [comment]
By removing "mode=imports", the URL works fine:
- Broken: https://cdn.skypack.dev/-/dset@v3.0.0-FxiY6gwKR0msQDjwfbYd/dist=es2020,mode=imports,min/dset.js
- Works: https://cdn.skypack.dev/-/dset@v3.0.0-FxiY6gwKR0msQDjwfbYd/dist=es2020,min/dset.js

**Comment by matthewp** [comment]
Hi @MarshallCB, thanks for reporting. Pinned URLs are now working. Existing pinned URLs should have been working all along, but the new ones were indeed broken but should be working now. If you find any that are not please let us know. Thanks again!
