### ISSUE TITLE
Problem with mime-types import

### ISSUE THREAD

**Issue by laughedelic** [pikapkg/cdn#140]
I'm trying to use https://github.com/googleapis/nodejs-bigquery library from Deno:

```typescript
import { BigQuery } from "https://cdn.skypack.dev/@google-cloud/bigquery@5.5.0";
const bq = new BigQuery();
```

running it with `/usr/bin/env deno run --allow-net --unstable` I get:

```
...
Download https://cdn.skypack.dev/-/mime-types@v2.1.29-ByBr9NIcUcuNUU4PRp3r/dist=es2020,mode=raw/mime-types
error: Import 'https://cdn.skypack.dev/-/mime-types@v2.1.29-ByBr9NIcUcuNUU4PRp3r/dist=es2020,mode=raw/mime-types' failed: 404 Not Found
    at https://cdn.skypack.dev/-/request@v2.88.2-ulr1Ytr85FrkyrElbXHD/dist=es2020,mode=imports/optimized/request.js:18:0
```

Trying to import `ruquest` or `mime-types` directly results in the same error, but the pinned version hash is different:

```typescript
import { request } from "https://cdn.skypack.dev/request@v2.88.2";
// or
import { mime } from "https://cdn.skypack.dev/mime-types@v2.1.29";
```

both give

```
Download https://cdn.skypack.dev/-/mime-types@v2.1.29-4PX06Oia6ww2a53Gcynt/dist=es2020,mode=raw/mime-types
error: Import 'https://cdn.skypack.dev/-/mime-types@v2.1.29-4PX06Oia6ww2a53Gcynt/dist=es2020,mode=raw/mime-types' failed: 404 Not Found
    at https://cdn.skypack.dev/mime-types@v2.1.29:15:0
```

I've seen similar issues reporting problems with concrete imports, but couldn't find anything related to `mime-types`. 

I'm new to Deno and JS/TS in general, so I might be doing something wrong and would appreciate any help.

**Comment by FredKSchott** [comment]
Fixed! This was an error introduced in a new version of the package builder, just pushed a fix and are rebuilding all old packages. All pinned URLs were unaffected (since they point to older, working versions).

Thanks for the heads up!

**Comment by laughedelic** [comment]
@FredKSchott Thanks for the quick fix!

Now if I run the same code:

```ts
import { BigQuery } from "https://cdn.skypack.dev/@google-cloud/bigquery@5.5.0";
const bq = new BigQuery();
```

I get 
```
error: Uncaught SyntaxError: Unexpected eval or arguments in strict mode
var arguments = is_1.arguments;
    ~~~~~~~~~
    at <anonymous> (https://cdn.skypack.dev/-/is@v3.3.0-0JynijvmtmCnyFvA37TY/dist=es2020,mode=imports/optimized/is.js:278:5)
```

Should I open a separate issue for that? Is this a Skypack issue at all?

**Comment by FredKSchott** [comment]
When I load that file (https://cdn.skypack.dev/-/@google-cloud/bigquery@v5.5.0-W9V6HSZwWbZriOTNBuCz/dist=es2020,mode=imports/optimized/@google-cloud/bigquery.js) I see
`import "/error/node:fs?from=@google-cloud/bigquery";` which means that this package relies on the Node `fs` package and can't run outside of Node.js. I don't think that this package will be able to run in the browser. 

Does Google ship a browser version of this library that we could somehow be loading instead?
