### ISSUE TITLE
do not re-export default if the package has no default export

### ISSUE THREAD

**Issue by isabella** [pikapkg/cdn#15]
`import('https://cdn.pika.dev/sucrase')` fails in deno because the `sucrase` package does not provide a default export.

```js
// https://cdn.pika.dev/sucrase
export * from '/-/sucrase@v3.15.0-CE22I1zp5eZXlZ1qUiU0/dist=es2019/sucrase.js';
export {default} from '/-/sucrase@v3.15.0-CE22I1zp5eZXlZ1qUiU0/dist=es2019/sucrase.js';
```

**Comment by FredKSchott** [comment]
Thanks for finding, fixed! You may need to clear your cache (Ctrl+shift+R) to get the update, since the file in question is set to cache locally in your browser.
