### ISSUE TITLE
Reacts with different hashes in the same version cause conflicts

### ISSUE THREAD

**Issue by gwsbhqt** [pikapkg/cdn#152]
I am trying to use skypack for all libraries recently, and most of them work perfectly, which makes me very satisfied. But there is an exception.

The react hash used by react-router-dom@6.0.0-beta.0 is different from the react hash used by other libraries. As a result, react was requested twice and the famous 321 problem appeared. In other words, there are multiple different versions of react.

I carefully compared the reacts between different hashes of the same version and found exactly the same content. I don't know what is the reason for this design, and how to solve this problem.

Did I misunderstand or did something wrong? Hope to help, thank you. 

![image](https://user-images.githubusercontent.com/16471930/112087097-545c7e80-8bc8-11eb-96d3-cf2745b64403.png)
![image](https://user-images.githubusercontent.com/16471930/112087325-b74e1580-8bc8-11eb-9790-0aeb9628c176.png)
![image](https://user-images.githubusercontent.com/16471930/112087348-c59c3180-8bc8-11eb-82a5-af09eea984f8.png)
![image](https://user-images.githubusercontent.com/16471930/112087362-cd5bd600-8bc8-11eb-9f2b-c12ad0d6b77f.png)

**Comment by allan-mobley-jr** [comment]
I have seen this as well...especially where a third party package internally relies on react.

**Comment by gwsbhqt** [comment]
In the case of the same version number, aren't they all the same? Wouldn't it be enough to just use the version number? Why add a hash suffix? I don't quite understand.

If possible, I hope that the official can add parameters after the url, allowing the version number or hash value of a certain library to be specified. Just like the alias option in webpack or rollup.

**Comment by allan-mobley-jr** [comment]
I was using: 'https://cdn.skypack.dev/react@17.0.1'

Another library I was skypacking, 'https://cdn.skypack.dev/dexie-react-hooks@1.0.6', has a normal npm reference to 'react' in its source code.

Skypack substitutes internal npm references with their skypack equivalent. In this case, it used a different hash. Not sure why. But the result is a different url.

The browser, however, treats every url as distinct and so two urls that deliver the same code would wind up causing the same code to be loaded twice.

What skypack is attempting to pull off is quite the feat, very impressive. I think with time they will iron out these issues.

**Comment by allan-mobley-jr** [comment]
As for hashes, I agree @gwsbhqt. 

Not sure why they are necessary if you are specifying a version in the url. That should be enough.

I'm sure skypack has a reason for doing this under the hood, so hopefully they will shed a little light on this.

**Comment by floschnell** [comment]
Took me quite a bit to get behind this ...
I have a dependency on preact/hooks as well as wouter-preact. wouter-preact also has a dependency on preact/hooks. Since hashes do not match, both refer to different modules and thus different global context variables.
Has anyone found a way to work around this until there's a fix?

**Comment by gwsbhqt** [comment]
@floschnell 

Or you can try this https://esm.sh/
