### ISSUE TITLE
Can't import type-fest in Deno

### ISSUE THREAD

**Issue by fjc0k** [pikapkg/cdn#16]
https://github.com/sindresorhus/type-fest

```ts
// x.ts
import { LiteralUnion } from 'https://cdn.pika.dev/type-fest'

type City = LiteralUnion<'bj' | 'sz', string>

export const city: City = 'bj'
```

`deno run -A x.ts`:

![image](https://user-images.githubusercontent.com/13151189/84101046-ba17b980-aa3f-11ea-82c6-98003c3af0a8.png)

**Comment by FredKSchott** [comment]
Fixed in the latest version of the package: https://github.com/sindresorhus/type-fest/pull/111/files

Also, fixed by our CDN to handle either case, in the future
