### ISSUE TITLE
[Bug] Common.js import & export variable conflict

### ISSUE THREAD

**Issue by zhoukekestar** [pikapkg/cdn#17]
Run it on Chrome directly.

```js
import('https://cdn.pika.dev/@formily/antd@v1.1.7').then(console.log);
```

We will get the error below:
`antd.js:1 Uncaught (in promise) SyntaxError: The requested module '/-/@formily/shared@v1.1.7/dist=es2019/shared.js' does not provide an export named 'log'`

If I load `shared` by this:

```js
import('https://cdn.pika.dev/-/@formily/shared@v1.1.7/dist=es2019/shared.js').then(console.log)
```

We can get like this:
```txt
{
  default: {
    log: ...
  }
}
```

So, I'm wondering which side will trigger this error. PikaCDN or Formily ?
Formily: https://github.com/alibaba/formily

**Comment by FredKSchott** [comment]
Thanks for posting. This is actually something that we need to handle better, and I'd love to use this package as an example.

## Fix needed on Pika CDN

Right now, we can't handle when a package does `import {Foo}` and `export {Foo}` in the same file from a Common.js module. We can fix this, it is not currently supported.

## Fix needed inside of @formily/antd

Their ESM entrypoint is exporting with conflicts: https://unpkg.com/browse/@formily/antd@1.1.7/esm/index.js

```js
import { SchemaForm, Form, Field } from './components';
export * from './components';
export { SchemaForm, Form, Field, // ...
// ERROR: Duplicate export: "SchemaForm"
```

Can you file an issue with them to resolve?

**Comment by zhoukekestar** [comment]
Hey, I had talked so much with The Formily Team and TRY so many methods to handle this situation. 
Because of the Formily's tech debt, it's not so easy to refactor it, and they are prepared to release the Formily 2.0, so we have to deal with it as simple as possible if we take care the ROI.

So here is our final resolution, bundle it locally (include node globals、multiple export、missed export and so on)
and push it to our CDN like this:

`http://xxx.alipay.aliyun-inc.com/formily.antd/1.2.0-beta.5/index.js` and use the import map to transform it.

**Comment by FredKSchott** [comment]
np! We got the fix on our end tested and working locally this evening, and will push out tomorrow.

Also FYI: Once fixed, I also ran into a new issue on the package: https://github.com/alibaba/formily/issues/911

Glad you found a solution, hope that we can get the package working on the CDN soon!
