### ISSUE TITLE
Inconsistency between cdn.skypack.dev and pkg.snowpack.dev (for @urql/core relative import)

### ISSUE THREAD

**Issue by JaredReisinger** [pikapkg/cdn#179]
I apologize in advance if this isn't the best place to raise this issue, but (a) there doesn't seem to be a repo for `pkg.snowpack.dev` that I could find (it's not in the snowpack monorepo or anywhere under snowpackjs), and (b) I think most of the same people are involved in both projects, so 🤞🏼 this is a reasonable place to track this.

As a part of looking into what I thought was a snowpack issue (https://github.com/snowpackjs/snowpack/issues/3393), I discovered that the redirection from pkg.snowpack.dev to cdn.skypack.dev is broken for at least one resource URL; namely, the relative link to `../common/5adc38f0-46a7d8df.js` from https://pkg.snowpack.dev/-/@urql/core@v2.1.2-BaGVb5xQ5BNV3TUNPHgq/dist=es2020,mode=imports/optimized/@urql/core.js.

_**When hitting cdn.skypack.dev directly:**_

  - https://cdn.skypack.dev/-/@urql/core@v2.1.2-BaGVb5xQ5BNV3TUNPHgq/dist=es2020,mode=imports/optimized/@urql/core.js

imports `../common/5adc38f0-46a7d8df.js`, which resolves to:

  - https://cdn.skypack.dev/-/@urql/core@v2.1.2-BaGVb5xQ5BNV3TUNPHgq/dist=es2020,mode=imports/optimized/common/5adc38f0-46a7d8df.js

... and all is well.

_**When using pkg.snowpack.dev, however:**_

  - https://pkg.snowpack.dev/-/@urql/core@v2.1.2-BaGVb5xQ5BNV3TUNPHgq/dist=es2020,mode=imports/optimized/@urql/core.js (which itself redirects to the skypack URL and works fine)

resolves the relative import `../common/5adc38f0-46a7d8df.js` to:

  - https://pkg.snowpack.dev/-/@urql/core@v2.1.2-BaGVb5xQ5BNV3TUNPHgq/dist=es2020,mode=imports/optimized/common/5adc38f0-46a7d8df.js

which looks identical (aside from the host) to the skypack URL, but which _actually_ redirects to:

  - https://cdn.skypack.dev/-/@urql/core@v2.1.2-BaGVb5xQ5BNV3TUNPHgq/dist=es2020,mode=imports/optimized/common@5adc38f0-46a7d8df.js (note the `@` in place of the `/` between `common` and `5adc38f0-46a7d8df` at the end of the URL)

which responds with:

```
Could not find resource exports/common@5adc38f0-46a7d8df.js
```

rather than the expected javascript content.

My hunch is that @urql/core's generated hash filename (`5adc38f0.js`) is causing confusion for some part of pkg.snowpack.dev/cdn.skypack.dev that parses URLs; instead of finding the snowpack/skypack hash (which appears to be separated from the original file name with a dash), it's seeing the _original_ filename hash (also 8 hex characters!) after the `/` and treating the URL specially, rather than passing it through to skypack unchanged.

**Comment by drwpow** [comment]
This is the right place to raise the issue! And yes it is the same people working on both 🙂. The short answer is that `pkg.snowpack.dev` is deprecated, and we need to just take the Pika URLs down eventually. A still-short-but-longer answer is that Skypack was basically Pika CDN 2.0, and is basically superior in all aspects. But it was a separate project, and we were running both side-by-side. We went through a long migration period of slowly redirecting everything from Pika CDN to Skypack, and now I believe most of Pika CDN is shut down save for some remaining URLs which don’t seem to be redirecting properly. We left them up as a convenience for people, but it seems now not everything is working properly. So please use skypack.dev for everything now going forward.

**Comment by JaredReisinger** [comment]
Got it, thanks!

In that case, I can amend my snowpackjs/snowpack#3397 PR so that it no longer keeps `pkg.snowpack.dev` as the default, requiring an explicit opt-in to get `cdn.skypack.dev`.  I'll flip it around so that `cdn.skypack.dev` is the default and anyone who still needs the snowpack shim has to explicitly ask for it.  This might be considered a breaking change... but I'll take that discussion over to snowpack since that's where the PR is.

I'm going ahead and closing this issue since what I'm hearing is that there's no intent to fix/update `pkg.snowpack.dev` since it's being deprecated.  (Which is fine by me; I'm now using skypack directly anyway.)
