### ISSUE TITLE
[Bug] relative import path not prefixed with /

### ISSUE THREAD

**Issue by OverGlass** [pikapkg/cdn#19]
Hello 👋   
First of all thanks for your work.
When I try to import Ramda in Deno : 
```javascript
 import * as pkg from 'https://cdn.pika.dev/ramda@^0.27.0'; 
```
I got this error :
```bash
error: relative import path "Iteration/Iteration" not prefixed with / or ./ or ../ Imported from "https://cdn.pika.dev/-/ts-toolbelt@v6.9.9-3Zszh3aMJpp7Yf6fMbxR/dist=es2019,mode=types/out/index.d.ts"
```

**Comment by FredKSchott** [comment]
Thanks for checking! I'm actually not sure what to make of that, see the file contents here:

```
declare module 'Iteration/Iteration' {
    /**
    An entry of **`IterationMap`**
    * `[0]`: Prev (<-)
    * `[1]`: Next (->)
    * `[2]`: Current **`string`**
    * `[3]`: Current **`number`**
    * `[4]`: Current Negative **`string`**
    * `[5]`: Cumulated Previous **`keys`** (for `Min` & `Max`)
    * `[6]`: Sign (- / 0 / +)
    */
    export type Iteration = [string, string, string, number, string, string, '-' | '0' | '+'];
}
declare module 'Misc/Iteration/Map' {
    import { Iteration } from "Iteration/Iteration";
   ...
```

It's importing from a local module that was declared above. But then Deno sees this as a "bad" import of some bare module name, so it fails. @kitson any idea what the correct output here should be? Or is this an issue in the package itself?

**Comment by venikman** [comment]
Looks like Deno has problems with it now: [Deno Issue](https://github.com/denoland/deno/issues/6448)

**Comment by kitsonk** [comment]
@FredKSchott it is @kitsonk 😄 sorry I didn't see it.

Hmmmm....  That is a strange `.d.ts`, very old school, using `declare module` instead of UMD declarations.  There are certainly type definitions that can work with Deno, but this one has all sorts of challenges.  I assume this is the `index.d.ts` provided by the package?

**Comment by FredKSchott** [comment]
Doh, sorry! It's actually the definitely typed, which we serve automatically if the package itself doesn't serve types. Happy to denylist this one if it's a wontfix to support this on Deno's end.

**Comment by OverGlass** [comment]
Well, I'll try to fix that type file and maybe do a PR to Ramda / definitely typed :)
Thank's for digging in that issue !

**Comment by FredKSchott** [comment]
np, thanks for filing!
