### ISSUE TITLE
[Package Issue] styled-components

### ISSUE THREAD

**Issue by numso** [pikapkg/cdn#20]
Importing the latest version of styled-components fails and I believe it may be related to changes made to solve https://github.com/pikapkg/cdn/issues/11.
```
// succeeds
import styled from 'https://cdn.pika.dev/styled-components@5.1.0'

// fails
import styled from 'https://cdn.pika.dev/styled-components@5.1.1'
```

---

Looks like styled-components checks to see if `process` is defined and uses it if it is:
https://github.com/styled-components/styled-components/blob/e56952a7d77be17dac9307dcee50e6eae5cd783f/packages/styled-components/src/constants.js#L6-L8

Loading styled-components@5.1.0 works fine. The code that uses process isn't touched:
https://cdn.pika.dev/-/styled-components@v5.1.0-JgjFjUuIFBQN8JGLCBlX/dist=es2017/styled-components.js

It looks like in version 5.1.1, the cdn-builder saw that `process` was referenced and auto-imported `/-/node:process` at the top which throws an error:
https://cdn.pika.dev/-/styled-components@v5.1.1-qiH7BbZT3rhzovSfpAFo/dist=es2017/styled-components.js

**Comment by FredKSchott** [comment]
Oh interesting! Great catch, just fixed in a new build accessible via https://cdn.pika.dev/styled-components
