### ISSUE TITLE
Possibility of supporting `exports` in `package.json`

### ISSUE THREAD

**Issue by Hawmex** [pikapkg/cdn#217]
Is it possible to support this feature?

In `package.json`:

```json
{
  "exports": {
    ".": "./dist/index.js",
    "./**/*": "./dist/**/*.js"
  }
}
```

In node, this works perfectly:

```js
import x from 'package/x';
```

I would like to see this in Skypack  CDN, too:

```js
import x from 'https://skypack.dev/package/x';
```

Current behavior:
```js
import x from 'https://skypack.dev/package/dist/x';
```

**Comment by drwpow** [comment]
Skypack aims to follow [Node.js’ package exports](https://nodejs.org/api/packages.html#packages_subpath_exports) implementation perfectly. To that extent, `**` isn’t allowed. But `*` should be treated as the same thing:

> All instances of `*` on the right hand side will then be replaced with this value, including if it contains any `/` separators.

Will check to see if this is the case

**Comment by Hawmex** [comment]
I checked its spec and you were right. But anyways, supporting `exports` by skypack could really help easily generating importmaps for browsers, without needing to implementing `exports` logic by generators. This way generators would only prefix package names with skypack cdn

### Example
```json
{
  "imports": {
    "some-package": "https://cdn.skypack.dev/some-package",
    "some-package/": "https://cdn.skypack.dev/some-package/"
  }
}
```

**Comment by Hawmex** [comment]
Closing since it seems that skypack already supports this correctly
