### ISSUE TITLE
[package issue] vaadin-details not imported properly

### ISSUE THREAD

**Issue by web-padawan** [pikapkg/cdn#23]
I'm trying to import `@vaadin/vaadin-details` in a Codepen and getting the error:

![Screenshot 2020-07-14 at 16 05 01](https://user-images.githubusercontent.com/10589913/87429086-f6fd4000-c5eb-11ea-8c87-6ace28c058c9.png)

Source: https://codepen.io/web-padawan/pen/yLyPKJP

**Comment by FredKSchott** [comment]
Fixed! Some internal files that were loaded by file path (instead of by package name) weren't getting their dependencies properly resolved.
