### ISSUE TITLE
psn-api missing from skypack

### ISSUE THREAD

**Issue by wescopeland** [pikapkg/cdn#235]
Hello!

I'm the author of [psn-api](https://www.npmjs.com/package/psn-api), which has been available on npm for a little over three weeks.

While the package is available to import via Skypack, it is unfortunately not available in search:
https://www.skypack.dev/view/psn-api (returns a 404)
https://www.skypack.dev/search?q=psn-api&p=1

Is there anything I can do to get this resolved? I'd love to add docs for using the library via Skypack.

**Comment by drwpow** [comment]
Hello! Yes this is a known issue with our npm crawler—it’s been having a bit of trouble lately. It runs off of npm’s good will and no-guarantees-API for their public tracker, which can have its own problems. Will investigate whether the problem is on their end or ours.

**Comment by wescopeland** [comment]
Looks like we're showing up now :-)

**Comment by drwpow** [comment]
Great! Sorry for the delay on this one.
