### ISSUE TITLE
UK Skypack is offline

### ISSUE THREAD

**Issue by lawless-m** [pikapkg/cdn#246]
Error 525 Ray ID: 6b7b7a470bf47767 • 2021-12-03 08:39:29 UTC

You Browser Working 

London Cloudflare Working

cdn.skypack.dev Host Error

**Comment by lawless-m** [comment]
```
matt@pig:/tmp$ telnet  172.67.74.194 80 # or  telnet  104.26.13.82 80 same result
Trying 172.67.74.194...
Connected to 172.67.74.194.
Escape character is '^]'.
GET /d3@7/ HTTP/1.1
HOST: cdn.skypack.dev


HTTP/1.1 520 Origin Error
Date: Fri, 03 Dec 2021 08:33:55 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-store, no-cache
CF-Cache-Status: MISS
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Tq7k%2FXjLNghzCQ8IYoK18rhtLnuuJEDXGmozHryDPqOknOQSwHtSrbyMO5Z0yyzqanPVzLWLFFFre6xC9%2FzsUUFPVsrLuC06uiGyHZsaU%2BgkqZG4ndeVlMJDxpIYLNqSEA%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 6b7b72049def76c9-LHR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400

b3
<html>
<head><title>520 Origin Error</title></head>
<body bgcolor="white">
<center><h1>520 Origin Error</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

0
```

**Comment by lawless-m** [comment]
OK it's back but that's not ideal.

**Comment by lawless-m** [comment]
Now I shall investigate how to self host, instead of relying on a CDN - how ironic

**Comment by drwpow** [comment]
Yeah we’ve been frustrated with this as well. It’s a known issue between Cloudflare and Vercel, mostly on Vercel’s end. It’s an SSL handshake error that doesn’t complete, and both companies blame the other.

When we made Skypack we wanted to make sure that it was multi-cloud, to be resilient. But this is one of the side-effects of multi-cloud few talk about: platform disagreements 😅. Overall, though, the issue has been minimized but sorry to hear it’s still happening for customers (our monitors don’t check all regions yet so we only catch NA outages)

**Comment by lawless-m** [comment]
Of course I was preparing for doing a demo today!

The fallacies

    The network is reliable;
    Latency is zero;
    Bandwidth is infinite;
    The network is secure;
    Topology doesn't change;
    There is one administrator;
    Transport cost is zero;
    The network is homogeneous.
