### ISSUE TITLE
[Package issue] Firebase

### ISSUE THREAD

**Issue by zachasme** [pikapkg/cdn#25]
I'm trying to get firebase working through skypack cdn, but none of the modules seem to work.

#### Import
```js
import firebase from "https://cdn.skypack.dev/firebase/app";
import "https://cdn.skypack.dev/firebase/auth";
import "https://cdn.skypack.dev/firebase/firestore";

const firebaseConfig = {
  // ...
};

firebase.initializeApp(firebaseConfig);
```

#### Result
```js
const auth = firebase.auth();
// Uncaught TypeError: (intermediate value).auth is not a function
const db = firebase.firestore();
// Uncaught TypeError: (intermediate value).firestore is not a function
```

#### Debugging
At the end of the request waterfall I see two requests for `https://cdn.skypack.dev/-/@firebase/app@v0.6.8-t1Qfw8PrkiBG7v6Bj7Xm/dist=es2020/@firebase/app.js` that only differ by the referrer http header (one for `auth` and one for `firestore`).

The modules are meant to register themselves on the `firebase/app` module, but if they don't import the exact same one I guess it won't work.

**Comment by FredKSchott** [comment]
We just solved a bug in our dependency resolver last night that I think was causing your problem here. I now get back a value for `firebase.auth`. Do you mind trying again?

**Comment by zachasme** [comment]
Thanks, now modules `auth` and `firebase` both work :+1: 

I still have trouble with `import "https://cdn.skypack.dev/firebase/analytics"`.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.skypack.dev/-/firebase@v7.16.1-OC48SHIQ8MvrQYgcTasb/dist=es2020,mode=raw/analytics/dist/index.esm.js. (Reason: CORS request did not succeed).`

I can't figure out what makes the request for the analytics module different from the other ones.

**Comment by FredKSchott** [comment]
Thanks for the heads up! Seems to be working now, and I'll follow up on why no CORS header came back 👍  If you run into any other odd packages, please lmk!

**Comment by andreasvirkus** [comment]
Still getting
```
Uncaught TypeError: firebase.auth is not a function
```

with 
```javascript
import firebase from 'https://cdn.skypack.dev/firebase/app'
import 'https://cdn.skypack.dev/firebase/auth'
import 'https://cdn.skypack.dev/firebase/firestore'
```

**Comment by drwpow** [comment]
@andreasvirkus can you post a complete code sample? I’m not sure where that’s coming from, exactly.

It should be noted that you may be relying on side-effects here which probably aren’t working as intended (the side-effects are probably designed for a Node environment, not the browser). You may need to do something like so (pseudo-code; hopefully you can adapt this for your needs):

```js
import firebaseApp from 'https://cdn.skypack.dev/firebase/app'
import firebaseAuth from 'https://cdn.skypack.dev/firebase/auth'
import firestore from 'https://cdn.skypack.dev/firebase/firestore'

const firebase = { ...firebaseApp, ...firebaseAuth, ...firestore };
```

**Comment by andreasvirkus** [comment]
I couldn't get it working with spreading the different modules into a single variable. Here's my complete (and rather bare-bones) firebase module:

```javascript
import firebaseApp from 'https://cdn.skypack.dev/firebase/app'
import firebaseAuth from 'https://cdn.skypack.dev/firebase/auth'
import firestore from 'https://cdn.skypack.dev/firebase/firestore'

const firebase = { ...firebaseApp, ...firebaseAuth, ...firestore }
const config = {/** ... */}

firebase.initializeApp(config)

export const db = firebase.firestore()
export const auth = firebase.auth()
export const currentUser = auth.currentUser

auth.onAuthStateChanged(console.info)
db.enablePersistence()

// firebase collections
export const avatarsCollection = db.collection('avatars')
export const getAvatar = (id) => avatarsCollection.doc(id).get()
```

Interestingly it only complains about `firebase.auth()` and not about firestore 🤔 

Edit: here's also the original snippet

```javascript
import firebase from 'https://cdn.skypack.dev/firebase/app'
import 'https://cdn.skypack.dev/firebase/auth'
import 'https://cdn.skypack.dev/firebase/firestore'

const config = {/** ... */}

firebase.initializeApp(config)

export const db = firebase.firestore()
export const auth = firebase.auth()
export const currentUser = auth.currentUser

auth.onAuthStateChanged(console.info)
db.enablePersistence()

// firebase collections
export const avatarsCollection = db.collection('avatars')
export const getAvatar = (id) => avatarsCollection.doc(id).get()
```
