### ISSUE TITLE
Types don't seem to work with deno

### ISSUE THREAD

**Issue by thomas-jeepe** [pikapkg/cdn#26]
When importing from pika cdn in deno, the types are derived from JS and it doesn't seem to use the actual typescript definitions.

Deno issue:

https://github.com/denoland/deno/issues/6799

**Comment by FredKSchott** [comment]
https://www.skypack.dev/ is the newest version of the Pika CDN, so I'd recommend updating your imports to point there. 

TypeScript types are no longer exported by default, and instead are opt-in via the `?dts` query param. See our docs for more: https://docs.skypack.dev/lookup-urls/lookup-urls#typescript-declarations

**Comment by thomas-jeepe** [comment]
Thanks for the response, but it still doesn't work and neither does the docs example.

You can test it on your own machine with:

```
echo "import { niceTypesdude } from 'https://cdn.skypack.dev/preact@^10.0.0?dts';const shouldFail = 0;" > test.ts

deno run -r test.ts 
Download https://cdn.skypack.dev/preact?dts
Download https://cdn.skypack.dev/-/preact@v10.4.6-vkaQ77UzUpPLLZkh5QlI/dist=es2020/preact.js
Check file:///home/justin/dev/test.ts
error: Uncaught TypeError: Cannot set property 'props' of undefined
    at d (https://cdn.skypack.dev/-/preact@v10.4.6-vkaQ77UzUpPLLZkh5QlI/dist=es2020/preact.js:1:807)
```

The file has invalid types but because no types are sent down, types are derived from the javascript file and it passes the type checking because `Component` is not the correct type.

**Comment by FredKSchott** [comment]
I believe that this issue is outdated, when I follow the above I get back a valid "x-typescript-types" header that Deno will follow.
