### ISSUE TITLE
Error in documentation, no type header returned for preact

### ISSUE THREAD

**Issue by esquevin** [pikapkg/cdn#29]
On https://docs.skypack.dev/lookup-urls/lookup-urls it says that `https://cdn.skypack.dev/preact?dts` should respond with a `X-TypeScrpt-Declarations` (typo here BTW, missing `i`).
But the header is not returned. 

It's there for `https://cdn.skypack.dev/react?dts` so the mechanism 

I don't know if it's a bug or if it's just that preact type have not been provided for skypack yet, so I ended up converting the preact d.ts files myself and referencing them locally. Can users contributes types to skypack ?

**Comment by FredKSchott** [comment]
Fixed! Thanks for filing
