### ISSUE TITLE
entities library not correctly ES-ified

### ISSUE THREAD

**Issue by aapoalas** [pikapkg/cdn#30]
Hello. I am trying to import htmlparser2 library through Skypack and one of the dependencies, entities library, has an [invalid ESM file](https://cdn.skypack.dev/-/entities@v2.0.3-JzTqWyCGs2VBJILKbv6q/dist=es2020,mode=raw/lib/decode_codepoint) on Skypack.

As can be seen, the file attempts to define the "__esModule" property on "exports" but exports has not been defined. Additionally the file uses the "require" function instead of "import".

Cheers.

**Comment by FredKSchott** [comment]
Hey! Thanks for filing. Blocked by https://github.com/pikapkg/skypack-cdn/issues/40, see explanation in that issue for more info on what's going on here.

**Comment by drwpow** [comment]
#40 went live this week! Hopefully this resolves your issue. Please let us know if you experience any other difficulties.
