### ISSUE TITLE
Update docs to ?dts instead of ?types

### ISSUE THREAD

**Issue by jlamb1** [pikapkg/cdn#31]
In this url, the docs state to add `?dts` to pull in automatic type declarations, also mentioned in https://github.com/pikapkg/skypack-cdn/issues/29

https://docs.skypack.dev/lookup-urls/lookup-urls

In the Deno specific docs, it says to add `?types` instead, which returns a 401 `Error: Malformed URL - Unknown query string`. ?types does work with the pika CDN link, so it looks like it's just beed updated.

https://docs.skypack.dev/code/deno

**Comment by FredKSchott** [comment]
Fixed! Thanks for filing
