### ISSUE TITLE
Preact 10.10.6 is failing to build

### ISSUE THREAD

**Issue by JoviDeCroock** [pikapkg/cdn#314]
The built files are looking good, which can be viewed [here](https://www.runpkg.com/?preact@10.10.6/package.json) but https://cdn.skypack.dev/preact is resulting in the following error https://cdn.skypack.dev/error/build:preact@v10.10.6-89mA0LKski3RVl1GcGJo

**Comment by jadjoubran** [comment]
This seems to be resolved now (https://cdn.skypack.dev/preact works)
