### ISSUE TITLE
@hotwired/turbo@v7.2.0" could not be built. 

### ISSUE THREAD

**Issue by Benoit1980** [pikapkg/cdn#319]
This package gives an error:
```
        <script type="module">
            import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';
        </script>


turbo@v7.2.0-jLjGyoEW3JseSmRfJh2M:13 Uncaught Error: [Package Error] "@hotwired/turbo@v7.2.0" could not be built. 
    at turbo@v7.2.0-jLjGyoEW3JseSmRfJh2M:13:7
```

https://cdn.skypack.dev/error/build:@hotwired/turbo@v7.2.0-jLjGyoEW3JseSmRfJh2M

/*
 * [Package Error] "@hotwired/turbo@v7.2.0" could not be built. 
 *
 * No build output found.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
throw new Error("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
export default null;

**Comment by edwinmartinson** [comment]
Hello, I also keep getting this error. All I get is a folder named error/build:@hotwired. And this displayed in the console:
[Package Error] "@hotwired/turbo@v7.2.0" could not be built.

**Comment by Benoit1980** [comment]
It is working now, thanks guys!

**Comment by Benoit1980** [comment]
Hello,

Sorry but the error restarted today again:
https://cdn.skypack.dev/error/build:@hotwired/turbo@v7.2.0-jLjGyoEW3JseSmRfJh2M


Thank you.

**Comment by jpforsyth** [comment]
Unfortunately, I'm still seeing this as broken.

**Comment by Benoit1980** [comment]
Yes me too

**Comment by jpforsyth** [comment]
> Unfortunately, I'm still seeing this as broken.

For anyone using Turbo with a direct script tag, you can try downgrading to v7.0.0:

`<script type="module">import hotwiredTurbo from "https://cdn.skypack.dev/pin/@hotwired/turbo@v7.0.0-9XNv1By6uiqRlBzQLO2d/mode=imports,min/optimized/@hotwired/turbo.js";</script>`

**Comment by Benoit1980** [comment]
> > Unfortunately, I'm still seeing this as broken.
> 
> For anyone using Turbo with a direct script tag, you can try downgrading to v7.0.0:
> 
> `<script type="module">import hotwiredTurbo from "https://cdn.skypack.dev/pin/@hotwired/turbo@v7.0.0-9XNv1By6uiqRlBzQLO2d/mode=imports,min/optimized/@hotwired/turbo.js";</script>`

Thank you very much

**Comment by jpforsyth** [comment]
You're welcome.

**Comment by capripot** [comment]
Version 8.0.4 is now also broken.

It works well on `https://cdn.jsdelivr.net/npm/@hotwired/turbo@8.0.4/+esm` for instance. Is that an issue with Skypack?

```
/*
 * [Package Error] "@hotwired/turbo@v8.0.4" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Failed to load node_modules/@hotwired/turbo/dist/turbo.es2017-esm.js
 *     Unexpected token (871:8) in @hotwired/turbo/dist/turbo.es2017-esm.js
 *   Install failed.
 *   Install failed.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@hotwired/turbo@v8.0.4\" could not be built. \n[1/5] Verifying package is valid…\n[2/5] Installing dependencies from npm…\n[3/5] Building package using esinstall…\nRunning esinstall...\nFailed to load node_modules/@hotwired/turbo/dist/turbo.es2017-esm.js\n  Unexpected token (871:8) in @hotwired/turbo/dist/turbo.es2017-esm.js\nInstall failed.\nInstall failed.");
throw new Error("[Package Error] \"@hotwired/turbo@v8.0.4\" could not be built. ");
export default null;
```

See also https://github.com/hotwired/turbo/issues/1172
