### ISSUE TITLE
`pouchdb-utils` re-exporting of `immediate` handled incorrectly

### ISSUE THREAD

**Issue by coldino** [pikapkg/cdn#35]
I hope this is the right place to raise an issue like this.

Testing how far I can get with PouchDB in Deno right now and I believe I've come across an incorrect transpilation:

`/-/pouchdb-utils@v7.2.2-qY2YTPiaUXQgDxYd7uyS/dist=es2020/pouchdb-utils.js`:
```js
import immediate from '/-/immediate@v3.3.0-WAoSeqvMd9fvv0ZjMbHn/dist=es2020/immediate.js';
import __commonjs_module0 from '/-/immediate@v3.3.0-WAoSeqvMd9fvv0ZjMbHn/dist=es2020/immediate.js';
export const {default : nextTick} = __commonjs_module0;
```
...where `immediate` is a simple function. Use of the `immediate` in this file is fine, but the re-export as `nextTick` attempts to use `immediate.default`, which is incorrect. Should just `export const nextTick = immediate`.

Source is [pouchdb/packages/node_modules/pouchdb-utils/src/index.js](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-utils/src/index.js), which plainly imports and re-exports the same symbol.

**Comment by FredKSchott** [comment]
Thanks for filing! As you can probably tell, tracked it down to a bit of bad handling of our CJS->ESM compatibility. 

I have a fix ready, but we'll want to test this more before deploying, since it would touch a few other packages (hopefully fixing more than just this one!) Will update this thread once deployed.

**Comment by drwpow** [comment]
Just released a CDN update and I believe this should be working now! We‘ve improved our CommonJS support and this seems to be generating correctly now (`nextTick` at least). Going to close this issue but please let us know if you experience any other difficulties with `pouchdb-utils`
