### ISSUE TITLE
Problem with search

### ISSUE THREAD

**Issue by soegaard** [pikapkg/cdn#36]
Hi,

Currently search fails and npms.io is blamed - but following the link to npms.io reveals
they are up and running.

https://www.skypack.dev/search?q=react-select

![image](https://user-images.githubusercontent.com/461765/89729063-62430200-da32-11ea-8d15-064b9d3113b8.png)

**Comment by soegaard** [comment]
Search works again. Closing.

**Comment by FredKSchott** [comment]
thanks for filing! Looks like we had an https cert issue on our end, so that error message wasn't totally right. 

Fixed it pretty soon after this was filed!
