### ISSUE TITLE
[Package issue] urql

### ISSUE THREAD

**Issue by zachasme** [pikapkg/cdn#38]
I'm trying to get `urql` working through skypack cdn, but something about the `graphql` imports appears to fail.

#### Import
```js
import { createClient } from "https://cdn.skypack.dev/urql@^1.9.7";
```

#### Result
```js
// Uncaught SyntaxError: import not found: GraphQLError
```

#### Debugging
I observe `@urql/core` doing `import { GraphQLError } from '/-/graphql@v15.3.0-RFpJ7Nx6d2obC1p2L5mX/dist=es2020,mode=raw/error/GraphQLError';` which, when imported directly, throws `Uncaught (in promise) ReferenceError: exports is not defined`.

**Comment by drwpow** [comment]
@zachasme, thanks for reporting! This was a bug in our CDN which has now been resolved. You should be able to load the `urql` package normally. Please let us know if you experience any more problems.
