### ISSUE TITLE
Various bugs (deep imports, dist es2017, firefox)

### ISSUE THREAD

**Issue by gingur** [pikapkg/cdn#39]
1. When using https://cdn.skypack.dev/pin/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/react.js vs https://cdn.skypack.dev/pin/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/min/react.js the `/min/` route does not include the "Preload Deep Imports" optimization (critical to avoid larger waterfall).

2. Not sure how, but using Firefox (79.0 64-bit) I intermittently see my dist getting set to es2017?

3. When getting a es2017 build (ex: https://cdn.skypack.dev/react@latest?dist=es2017) a http://cdn.skypack.dev/-/@pika/polyfill@v0.0.3-ohSHYfzCb0txwnYCLjl9/dist=es2017/polyfill.js is defined that is CJS + Webpack?

4. When getting a es2017 build (ex: https://cdn.skypack.dev/react@latest?dist=es2017) a https://cdn.skypack.dev/-/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/dist=es2017/react.js is defined that is CJS and uses `require`?

**Comment by FredKSchott** [comment]
Thanks for digging in and taking the time to file all of these! Really appreciate the help and sorry for the confusing experience. 

We just pushed out a batch of fixes that contained some fixes for pinned URLs, which should solve the issues you've outlined here. In general, these were related to bad cache keys in the pinned URL, which caused browsers of different "dist" (es2020, es2017, etc) to share cached responses that didn't match their expected dist.

Let me know if you run into any other issues moving forward!

**Comment by gingur** [comment]
I'm seeing an issue with "Preload Deep Imports" not being provided again. Example https://cdn.skypack.dev/pin/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/min/react.js

Output for Chrome 85.0.4183.102 (Official Build) (64-bit) on Windows 10
```js
/*
 * Skypack CDN - react@16.13.1
 * Remove "min" from url for additional help & instructions.
 */

export * from '/-/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/dist=es2020,min/react.js';
export {default} from '/-/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/dist=es2020,min/react.js';

// Perf Optimization: Preload Deep Imports
```
