### ISSUE TITLE
ESM modules export twice

### ISSUE THREAD

**Issue by Richienb** [pikapkg/cdn#4]
ky-universal uses ESM exports but is unable to use the `module` field due to it having to support Node.js and browsers. As a result, Pika CDN assumes that commonjs exports are used. See: https://cdn.pika.dev/-/ky-universal@v0.6.0-PkvboYA0oh0SZC5pFSZU/dist=es2019/ky-universal.js

**Comment by FredKSchott** [comment]
Fixed! Thanks for your patience
