### ISSUE TITLE
[docs] JavaScript example does not work in Chrome and Firefox because it violates the Content Security Policy directive

### ISSUE THREAD

**Issue by coderbyheart** [pikapkg/cdn#43]
When I run the example shown on https://docs.skypack.dev/code/javascript

```javascript
(async () => { 
  const React = await import('https://cdn.skypack.dev/react'); 
  console.log(`Hello, React v${React.version}`);
})();
```

both Chromium (Version 84.0.4147.125 (Official Build) Arch Linux (64-bit)) and Firefox (79.0 (64-bit)) will not load the script:

> Refused to load the script 'https://cdn.skypack.dev/react' because it violates the following Content Security Policy directive: "script-src 'self' gstatic.gitbook.com 'unsafe-inline' *.firebaseio.com *.google.com polyfill.io cdn.lr-ingest.io cdn.logrocket.io *.stripe.com *.clearbit.com *.google-analytics.com *.iframe.ly *.gstatic.com cdnjs.cloudflare.com *.intercom.io *.intercomcdn.com gitbookio.github.io https://app.intercom.io https://widget.intercom.io https://js.intercomcdn.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> VM278:4 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://cdn.skypack.dev/react

![image](https://user-images.githubusercontent.com/188915/90240809-3a84dd00-de2a-11ea-88ae-45f006f9a95d.png)

**Comment by FredKSchott** [comment]
Oh right,  some sites won't let you run that in the console, I didn't think that our docs site was one of them 🤦 

Will look into clarifying docs

**Comment by drwpow** [comment]
Thanks! Added a note to the docs on paying attention to your site’s CSP: https://app.gitbook.com/@skypack/s/skypack/code/optimize-for-production#content-security-policy-csp

**Comment by FredKSchott** [comment]
I think I think @coderbyheart was referring to the example on this page: https://docs.skypack.dev/code/javascript

Just updated it to point to the skypack REPL (www.skypack.dev/react) to run any examples. That's what it's there for, anyway :)

**Comment by coderbyheart** [comment]
> I think I think @coderbyheart was referring to the example on this page: https://docs.skypack.dev/code/javascript
> 
> Just updated it to point to the skypack REPL ([www.skypack.dev/react](http://www.skypack.dev/react)) to run any examples. That's what it's there for, anyway :)

Yes, thanks. It's now more obvious where to put the code.
