### ISSUE TITLE
[Package issue] lit-element and lit-html can't be used together

### ISSUE THREAD

**Issue by alex4o** [pikapkg/cdn#44]
When the directives from lit-html are used inside of lit-element they are not recognized, because the directive imports a different lit-html.js file imported from another place. The imports work properly when jspm is used.

Here is demo code: https://codesandbox.io/s/cool-fog-7pfcb?file=/index.js
Here is a working version using the skypack-cdn: https://codesandbox.io/s/broken-sun-81ys1?file=/index.js

Have a nice day.

**Comment by cletusw** [comment]
I'm having the same issue with [haunted](https://github.com/matthewp/haunted) & [lit-html](https://github.com/Polymer/lit-html).

**Comment by matthewp** [comment]
@cletusw Is your issue with using lit-html's directives with Haunted (as @alex4o's problem shows)? Just using Haunted by itself seems fine here.

**Comment by matthewp** [comment]
I think this is because there isn't an export map for lit-html. If there were an export map that contains paths for all of the directives everything should link up correctly. Will attempt to confirm.

**Comment by cletusw** [comment]
Correct. This works:

```js
import {...} from 'https://jspm.dev/haunted@4.7.0';
import {...} from 'https://jspm.dev/lit-html@1/directives/repeat.js';
```

But the equivalent using skypack did not because the lit-html referenced from haunted did not match the one imported directly.

**Comment by matthewp** [comment]
@cletusw Thanks! Yeah, it's about directives then. That makes sense and helps with investigating.

**Comment by FredKSchott** [comment]
Fixed! Thanks for your patience on this one while we implemented better import map support. We now respect lit-html's import map in the v2 beta branch, and have backported it to v1.30 as well. This lets us bundle the package by valid package entrypoint.

**Comment by cletusw** [comment]
Awesome! Thanks.
