### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by benmccann** [pikapkg/cdn#46]
https://docs.skypack.dev says "Skypack is the first CDN to automatically address this problem by skipping unnecessary compilation & polyfilling for on modern browsers" - notice the "for on"

btw, I used to use Gitbook for one of my projects, but they stopped supporting the opensource version so I moved to Docusaurus. probably not worth switching, but thought I'd make you all aware of it just in case it was helpful

**Comment by FredKSchott** [comment]
Thank you! Fixed! And thanks for all of your work on Sapper :)

Yea, we're enjoying it for now but are definitely keeping an eye on Docusaurus
