### ISSUE TITLE
Package @esri/arcgis-html-sanitizer doesn't load

### ISSUE THREAD

**Issue by dasa** [pikapkg/cdn#49]
https://www.skypack.dev/npm/@esri/arcgis-html-sanitizer seems to hang...

<img width="857" alt="image" src="https://user-images.githubusercontent.com/828058/91883357-2833dd00-ec39-11ea-87e5-df85c264f74c.png">

**Comment by FredKSchott** [comment]
Looks like our npm crawler got backed up, fixed and re-populating now! This should show up in a couple of hours, at the latest

**Comment by dasa** [comment]
The page is still hanging for me.

**Comment by FredKSchott** [comment]
Bah, okay thanks for checking. Sometimes packages are missed from the npm registry that we follow for updates, sorry about that.

We're actively working on a new API to move the catalog to, and will try to debug this more as a part of this work

**Comment by marcuslindblom** [comment]
Same here for me, hangs without error

**Comment by drwpow** [comment]
Thanks for raising this. We are going to release a big updates to our search catalog soon which should fix this issue. Thanks for your patience!

**Comment by drwpow** [comment]
The new skypack.dev is now live! I’m seeing https://www.skypack.dev/view/@esri/arcgis-html-sanitizer up-to-date. But please let me know if there is anything we can do to improve this.
