### ISSUE TITLE
apollo-server-lambda 502 Bad Gateway

### ISSUE THREAD

**Issue by rodrigorm** [pikapkg/cdn#5]
Hi, I am trying to import `apollo-server-lambda` and getting an error 502 Bad Gateway when requesting URL https://cdn.pika.dev/-/apollo-server-lambda@v2.13.1/dist=es2019/apollo-server-lambda.js

**Comment by FredKSchott** [comment]
Yup, looks like an issue in this package: https://cdn.pika.dev/-/apollo-server-env@v2.4.4/dist=es2019/apollo-server-env.js

From our internal logs:

```
✖ snowpack failed to load node_modules/apollo-server-env/dist/index.browser.js
-   Illegal reassignment to import 'commonjsHelpers'
```

**Comment by FredKSchott** [comment]
If it helps, even if it loaded properly this package won't work on Deno, since it was written specifically for Node.js, uses node.js builtins that don't exist on Deno, etc.
