### ISSUE TITLE
Provide a dynamic import statement for packages (which works in browser REPL)

### ISSUE THREAD

**Issue by snickell** [pikapkg/cdn#51]
I've been absolutely loving Skypack, its the best thing ever. I'm finding that many of my otherwise JS savvy programmer friends didn't even know ESM modules imported from URLs were a thing, so new Skypack discovers are likely to know very little too. 

I suspect that when people are trying new things, they're likely to use DevTools console, but static import statements are (disappointingly, but understandably) one of the few JS statements you cannot make in Devtools (at least in 2020).

I would suggest including the dynamic import version of each package in the "copy pastable" source, which will educate people how to use ESM features with REPL, and also may be the link they actually first use.

```
// 👋 Welcome to Skypack! 

// Skypack is a Package Delivery Network (PDN) for everything on npm.
// Load any JavaScript package directly in the browser.

// Try loading the "canvas-confetti" package in the example below. 
// When you have something you like, copy the code onto your website!

import * as pkg from 'https://cdn.skypack.dev/canvas-confetti@^1.0.3';
console.log('canvas-confetti loaded:', pkg);

// FYI, if you want to import in a devtools console you can do:
// const { default: Confetti } = await import('https://cdn.skypack.dev/canvas-confetti');
```

**Comment by FredKSchott** [comment]
@snickell thanks for the message! We're actually tackling a full redesign of this page as we speak, so this would be good feedback for @drwpow to see.

**Comment by FredKSchott** [comment]
Shipped in the new catalog release! Example: https://www.skypack.dev/view/canvas-confetti
