### ISSUE TITLE
Type declarations assumed to be index.d.ts

### ISSUE THREAD

**Issue by Liamolucko** [pikapkg/cdn#52]
I'm trying to use a package named `fast-png` (in Deno), and the `?dts` flag isn't working properly. I did some investigation and found that it was due to one of its dependencies `iobuffer`'s type declarations not being named `index.d.ts`.

It expands the original line
```typescript
import { IOBuffer } from 'iobuffer';
``` 
into
```typescript
import { IOBuffer } from '/-/iobuffer@v5.0.2-M34vHwNqvHxUuAPbIk4L/dist=es2020,mode=types/index.d.ts';
```
when the actual type declarations are at `lib/IOBuffer.d.ts`.

It also seems to lead to `X-TypeScript-Types` being missing when importing `iobuffer` directly.

**Comment by drwpow** [comment]
It looks like for iobuffer we‘re not sending the [`X-TypeScript-Types` header](https://docs.skypack.dev/code/deno) correctly, so it seems like `types/index.d.ts` is just a guess Deno is making when it can’t find the type declarations. Will investigate why that is.

**Comment by drwpow** [comment]
Update: we are going to push an update to the CDN soon which should resolve this. I’m seeing the correct types load on our staging builder. We’ll push the update as soon as we run some more tests to make sure we‘re not introducing any regressions.

**Comment by FredKSchott** [comment]
Fixed!
