### ISSUE TITLE
rollup-plugin-skypack-resolver

### ISSUE THREAD

**Issue by vinicius73** [pikapkg/cdn#55]
Just sharing my package to support skypack cdn in rollup projects

https://www.npmjs.com/package/@vinicius73/rollup-plugin-skypack-resolver

Is a very simple but usefull plugin. Please consider this package in your docs.

**Comment by FredKSchott** [comment]
Thanks for sharing! This is fantastic, I'd love to point users towards this until we add an official plugin

/cc @drwpow

**Comment by drwpow** [comment]
Thanks again for sharing! For now I added it here: https://docs.skypack.dev/skypack-cdn/code/optimize-for-production#build-tools

Keep in mind we may shift this around as we work on the docs this month, but I’d like to keep a note to it visible somewhere (more visible than this issue, at least 😉)
