### ISSUE TITLE
Allow `eval` usages

### ISSUE THREAD

**Issue by stramel** [pikapkg/cdn#58]
I'm attempting to import `netlify-cms`. The build fails due to `eval()` usages. I have brought this up and it appears all usages are safe. 

**Attempted:**

`await import('https://cdn.skypack.dev/netlify-cms')`

**Error:**

```js
/*
 * [Package Error] "netlify-cms" could not be built. 
 * 
 *   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
 *   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
 *   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
 *   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
 * 
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/pikapkg/cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://pika.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"netlify-cms\" could not be built. \nUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification\nUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification\nUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification\nUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification");
throw new Error("[Package Error] \"netlify-cms\" could not be built. ");
export default null;
```

The issue where I brought up the `eval()` usages. https://github.com/netlify/netlify-cms/issues/4367

This might be an issue with properly differentiating between warnings and errors. Another option would be to provide a manual way to accept certain errors/warnings.

**Comment by FredKSchott** [comment]
That's correct, I'd thought that this was just a warning. If that's blocking the build entirely, that's a bug! Will take a deeper look.

**Comment by drwpow** [comment]
Still having an issue with this one. I see the following: `eval("require('util').inspect")` and `var crypto=eval("require('crypto')"),Buffer=eval("require('buffer').Buffer"`.

Weirdly enough, `eval("import('/thing')")` actually works, but we can’t transform sync `require()`s to static `import` statements in this case, in the context of `eval`.

I’m afraid this version of `netlify-cms` may not be deliverable on Skypack :/ (and at `4 MB` we’d probably recommend you didn’t anyway 😉 ).

Sorry—I know this isn’t a solution but I think I’m going to close this ticket for this package specifically. But I’ll keep an eye on any other `eval`s I come across!
