### ISSUE TITLE
Docs: Non-working example link

### ISSUE THREAD

**Issue by rschristian** [pikapkg/cdn#61]
Hello, on the "Package Scores" page, you use Preact as an example under the "Why" of "Export Map".
Link: https://docs.skypack.dev/package-authors/package-checks#why-2

The Preact link here is non-functional though (404). The link sends users to https://www.skypack.dev/npm/preact, but I believe the correct route is https://www.skypack.dev/view/preact

**Comment by FredKSchott** [comment]
Thanks, fixed!
