### ISSUE TITLE
Firebase "Duplicate export 'default'" problem

### ISSUE THREAD

**Issue by mbleigh** [pikapkg/cdn#7]
If you look at https://cdn.pika.dev/-/firebase@v7.14.4-RNh3lO0slNRDOjcVbuZy/dist=es2019/firebase.js you can see that there are two default exports:

```
export { default } from "..."
export default null;
```

I'm not sure what the Pika CDN does to transform modules, but this one is obviously a problem. Can it be fixed?

**Comment by mbleigh** [comment]
My best guess is that Pika isn't expecting the default export to be directly exported out of a different module and adds a default export as a matter of course, which breaks in this case?

**Comment by FredKSchott** [comment]
Yup, that's correct. We do this at all to better support our CJS->ESM transforms. 

We can be smarter about it tho, and only `export default null` if no named export is detected. Will implement this asap

**Comment by mbleigh** [comment]
Any update on a fix for this? Blocking me from being able to easily use Firebase in Snowpack apps, which I'm very keen to do! 😄

**Comment by FredKSchott** [comment]
Fixed! Sorry for the delay on that, just tested it and importing works great!
