### ISSUE TITLE
npm package missing from CDN

### ISSUE THREAD

**Issue by manzt** [pikapkg/cdn#71]
I recently published (a couple of days ago) a pure ESM module [`zarr-lite`](https://github.com/manzt/zarr-lite) to npm and haven't seen it mirrored on the skypack cdn. Is there additional metadata required to have a package be discoverable?

I am able to import from unpkg, but I'd like to use skypack! 

```
const zarr = await import('https://unpkg.com/@manzt/zarr-lite/index.js') // works
```

https://www.skypack.dev/search?q=%40manzt%2Fzarr-lite&p=1

**Comment by FredKSchott** [comment]
This is loadable on Skypack CDN: https://cdn.skypack.dev/@manzt/zarr-lite

But you're right, I'm not sure why it's not showing up in our search catalog. @drwpow to track

**Comment by manzt** [comment]
Interesting, I'm getting an error when importing in observable:

https://observablehq.com/@manzt/import-error-from-skypack-cdn

`package.json`:

```
{
  "name": "@manzt/zarr-lite",
  "version": "0.0.5",
  "description": "A partial Zarr Implementation for reading array chunks.",
  "type": "module",
  "module": "index.js",
  "files": [
    "index.js",
    "httpStore.js"
  ],
  "exports": {
    ".": "./index.js",
    "./httpStore": "./httpStore.js"
  },
  "scripts": {},
  "keywords": [],
  "author": "Trevor Manz",
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "esbuild": "^0.8.6"
  }
}
```

**Comment by FredKSchott** [comment]
Ah good catch, you're right. Those `import()` calls were messing with something in our JS parser (bug on our end, not yours), pushing out a fix now!

**Comment by manzt** [comment]
Wow, thanks so much for the quick fix / taking a look into it!

**Comment by FredKSchott** [comment]
np! appreciate you letting us know

**Comment by FredKSchott** [comment]
fix deployed! observable notebook is now loading 👍 for me.

I'll follow up with @drwpow about why the catalog isn't including this package. Most likely, npm didn't send us an update about the package, which usually then gets picked up when we do a full resync.
