### ISSUE TITLE
Requestion @^x.yz version does not work anymore

### ISSUE THREAD

**Issue by esquevin** [pikapkg/cdn#72]
Suddenly requests made for
https://cdn.skypack.dev/preact@^10.4.4?dts  returned the 10.5.6 version

seems the ^ is not recognized anymore and needs to be removed.

**Comment by FredKSchott** [comment]
That is correct as far as I understand, what were you expecting? 

See: https://semver.npmjs.com/ (put in preact and `^10.4.4`, and see 10.5.6 as the most up-to-date matched version).

**Comment by esquevin** [comment]
Sorry 🤦‍♂️

For some reason I though that I had pinned down the version of preact. So I was surprised to see that skypack returned 1.5.6 and though that there was an error in _your_ code… How arrogant of me…

I apologize for wasting your time, and give you all my thanks for skypack
