### ISSUE TITLE
[Package issue] Ant Design

### ISSUE THREAD

**Issue by tommywalkie** [pikapkg/cdn#73]
_Probably_ related to https://github.com/snowpackjs/skypack-cdn/issues/63.

If directly using the `antd` package which has for example `@ant-design/icons` as dependency. Snowpack tries to retrieve a certain `AntdIcon` module within [https://cdn.skypack.dev/-/@ant-design/icons@v4.3.0.../lib/icons/components/AntdIcon](https://cdn.skypack.dev/-/@ant-design/icons@v4.3.0-1W8DahpJX9ChIsNtJsFN/dist=es2020,mode=raw/lib/icons/components/AntdIcon) which results in CORS issues :

```
Not found: @ant-design/icons/4.3.0/1/lib/icons/components/AntdIcon
```

**Comment by tommywalkie** [comment]
Reproduced the issue on [Codepen](https://codepen.io/tommywalkie/pen/GRqeQey) with the following code, the mentionned error appears on Firefox Devtools console.

```js
import React, {createElement} from 'https://cdn.skypack.dev/react'
import {render} from 'https://cdn.skypack.dev/react-dom'
import {Card} from 'https://cdn.skypack.dev/antd'

const App = () => <div>
  <p>Lorem ipsum dolor sit amet</p>
  <Card>Card content</Card>
</div>

render(createElement(App), document.getElementById('root'))
```

**Comment by FredKSchott** [comment]
Thanks for the ping!

antd is probably the hardest-to-optimize package on our CDN at the moment: it's a mix of references to individual files within it's own dependencies (which are hard for us to optimize) which point to CJS files that are over-transpiled to include @babel/runtime and other things that we need to workaround.

Here's what I'm going to suggest: I'm going to push a change that will bundle antd into a single JS file on our CDN which will unblock this package and result in a better performance story for most users. Then we can work on the workarounds seperately, possibly with help from / in collaboration with the antd team if they're interested.

**Comment by FredKSchott** [comment]
Fixed! I now see your codepen running, and here is a version of it with styles added: https://codepen.io/fks/pen/mdEYQLq

**Comment by fakership** [comment]
you say it is fixed, but there is also 'Uncaught SyntaxError: The requested module 'https://cdn.skypack.dev/antd' does not provide an export named 'Card' 
 at https://cdpn.io/cp/internal/boomboom/index.html?editors=1111&key=index.html-52200222-1b37-243c-eaa3-89a804d636ab:0' in https://codepen.io/fks/pen/mdEYQLq

**Comment by fakership** [comment]
@FredKSchott
