### ISSUE TITLE
Tiny slider import not working (export is null)

### ISSUE THREAD

**Issue by klaasgeldof** [pikapkg/cdn#74]
To import the **tiny-slider** package, I should be able to do:

```js
import { tns } from 'https://cdn.skypack.dev/tiny-slider'
```

However this doesn't work, as it exports `null`.

See the last lines of this file: https://cdn.skypack.dev/-/tiny-slider@v2.9.3-ReBtZ4kmWjkFCju8PbOa/dist=es2020/tiny-slider.js

**Comment by FredKSchott** [comment]
Based on their README, I believe skypack is behaving as expected here:
https://github.com/ganlanyuan/tiny-slider#3-call-tns

---


#### 3. Call tns()
Option A: Add tiny-slider.js to your page:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js"></script>
<!-- NOTE: prior to v2.2.1 tiny-slider.js need to be in <body> -->
```

Option B: Import `tns` via `webpack` or `rollup`:
```javascript
// yourScript.js
import { tns } from "./node_modules/tiny-slider/src/tiny-slider"
```

Option C: Import `tns` directly start from v2.8.2
```html
<script type="module">
  import {tns} from './src/tiny-slider.js';

  var slider = tns({
    container: '.my-slider',
    items: 3,
    slideBy: 'page',
    autoplay: true
  });
  </script>
```

---

Loading tiny-slider directly seems to match option A, where it "just works" on the page:

```
import 'https://cdn.skypack.dev/tiny-slider';
// seem like this should do something on the page?
```

Option B & C seem ask you do to this:

```
import { tns } from 'https://cdn.skypack.dev/tiny-slider/src/tiny-slider.js';
```

But, this sends you into our de-optimized "individual file" mode. It would be better if they could support the ESM interface via the package name on its own. It could be worth filing an issue with the repo about adding a `"module": "./src/tiny-slider.js"` entrypoint for bundlers like Rollup, Webpack, and CDNs like Skypack to take advantage of.

**Comment by FredKSchott** [comment]
If they aren't receptive, then you could add an export map workaround to https://github.com/snowpackjs/DefinitelyExported

**Comment by klaasgeldof** [comment]
Thanks for your feedback, this works indeed!
Still finding my way in this new world of imports 🙂
Keep up the good work!
