### ISSUE TITLE
the espree module stopped working via skypack in the last few days

### ISSUE THREAD

**Issue by mreinstein** [pikapkg/cdn#75]
this works in node/npm:

```javascript
import espree from 'espree'

const token = {
    text: `export default function foo () {
        return "I am Foo!"
    }`
}

const program = espree.parse(token.text, { ecmaVersion: 9, sourceType: 'module' })
```

(I'm using espree@7.3.0 in my `package.json`)

this fails in my browser (latest chrome:)
```html
<!DOCTYPE html>
<html>
<body>
<script type="module">

import espree from 'https://cdn.skypack.dev/espree'

const token = {
    text: `export default function foo () {
        return "I am Foo!"
    }`
}

const program = espree.parse(token.text, { ecmaVersion: 9, sourceType: 'module' })

</script>

</body>
</html>
```

Error:
```
espree.js:840 Uncaught TypeError: Cannot read property 'Parser' of null
```

What's odd is this _used_ to work in the browser, like as of 2-3 days ago. `espree` hasn't published a new npm module or pushed anything consequential to git in several months, so I have to believe something internal with skypack's build service failed.

Btw, thanks for an _amazing_ service! Apart from this one hiccup I'm absolutely in love with the workflow this service enables. ❤️

**Comment by drwpow** [comment]
Thanks for filing! Yes we actually did ship an upgraded version of our package builder, which expanded support to a ton of packages that didn‘t load before, and we also improved our React support!

Unfortunately it seems that something changed within `acorn` and that wasn‘t on our testing list. I do see the error you‘re describing not in `espree` but in `acorn`.

But good news is that we are planning another upcoming version of our package builder within the next week or two. I’ll be sure to add this package to our E2E tests to make sure it‘s fixed soon.

**Comment by mreinstein** [comment]
@drwpow  thanks for the follow-up!

> I do see the error you‘re describing not in espree but in acorn.

I was able to import `acorn` directly from skypack without problems. I'm guessing that espree not providing an es module may have something to do with it (I'm sure skypack internally has some magic to transform these packages.) 
I've opened an issue on the espree project to maybe provide an es module entry point too. :) https://github.com/eslint/espree/pull/458


> But good news is that we are planning another upcoming version of our package builder within the next week or two. 

Nice. Any details available on what the new version will have? Is skypack's package builder changelog exposed anywhere?

by the way, in somewhat related news, did you see this yet? Pretty awesome! https://github.com/nodejs/node/issues/20494

**Comment by FredKSchott** [comment]
@mreinstein thanks again for the ping on this, and thanks for the kind words! Glad you're enjoying the CDN! 

Just triaged this issue a bit more and it looks like it was related to a regression in our ESM<>CJS cross compatibility. Because espree is CJS and acorn is ESM, our builder missed that acorn should have been imported as a namespace (`import * as acorn`) instead of a default (`import acorn`). 

Just pushed out the fix to get this resolved, and can confirm that your code snippet above now runs our my machine. Can you confirm to let us know?

>  Is skypack's package builder changelog exposed anywhere?

Not currently, but I love this idea!

**Comment by mreinstein** [comment]
> Can you confirm to let us know?

confirmed, https://cdn.skypack.dev/espree is workin' great!
