### ISSUE TITLE
[Package Issue] Vue library behaving unexpectedly with this.$el

### ISSUE THREAD

**Issue by callumacrae** [pikapkg/cdn#78]
Hey! First time using skypack - big fan so far 😄 

However, importing Vue through skypack is behaving a bit strangely - `this.$el` is a comment node, not the expected div element.

Reproduce here: https://codepen.io/callumacrae/pen/QWERqZa?editors=1010

Expected output: `<div id="app"></div>` (as node)
Actual output: `<!--function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }-->` (as node)

Have replicated on both codepen and jsfiddle. The problem does not occur when Vue is imported through cdnjs.

The problem also occurs with both Vue 2 and 3, which is strange as Vue 3 was a complete rewrite.

**Comment by FredKSchott** [comment]
It looks like Codepen is hiding an important warning:

```
vue.js:619 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

`import 'vue'` is meant to return the Vue runtime (without the compiler), what you really want is `import 'vue/dist/vue.esm.js'` which also includes the compiler. However, since that's an individual file within the package, we serve it unoptimized and it dies at a process.env reference. 

Agreed that we need a better story here for Vue!

**Comment by drwpow** [comment]
Added a troubleshooting guide to docs.skypack.dev here: https://docs.skypack.dev/troubleshooting-and-faq#q-im-having-trouble-with-vue. Hopefully this is helpful, and helps other people as well. Thank you for raising the issue!

**Comment by MHarrison22** [comment]
I'm receiving a 404 on the import following the [documentation](https://docs.skypack.dev/troubleshooting-and-faq#q-im-having-trouble-with-vue):

`import * as Vue from 'https://cdn.skypack.dev/vue/dist/vue.esm-browser.prod.js';`

**Comment by drwpow** [comment]
Ah shoot. That was a typo on my part; I forgot that Vue 3 isn‘t the `latest` version yet. I’ll update the docs, but you can use:

- Vue 2.x: `https://cdn.skypack.dev/vue/dist/vue.esm.browser.min.js`
- Vue 3.x: `https://cdn.skypack.dev/vue@next/dist/vue.esm-browser.prod.js`

**Comment by MHarrison22** [comment]
Thank you - appreciate it!

**Comment by callumacrae** [comment]
Probably wise to use `https://cdn.skypack.dev/vue@2/dist/vue.esm.browser.min.js` for vue 2 so that it doesn't break when vue 3 becomes `latest`!
