### ISSUE TITLE
Duet Date Picker

### ISSUE THREAD

**Issue by chriscoyier** [pikapkg/cdn#82]
Ran across this nice date picker:
https://github.com/duetds/date-picker

Tried to use it here:
https://codepen.io/chriscoyier/pen/bGwbNYm

Loading failed message:

```
GET https://cdn.skypack.dev/new/@duetds/date-picker@v1.1.0/dist=es2020/dist/loader net::ERR_FAILED
```

**Comment by drwpow** [comment]
Aw, snap! And we recommend that package, too, on Skypack 😅.

This actually seems to be an issue with `@duetds/date-picker`. It seems their ESM build is broken, as it [points to a completely empty file](https://unpkg.com/browse/@duetds/date-picker@1.1.0/dist/esm-es5/index.js). I’ve [opened an issue on the original repo](https://github.com/duetds/date-picker/issues/59). But we should probably have a more clear error message that this is an empty package, shouldn’t we (or at least try and build the CommonJS version if ESM failed)?

Thanks for reporting!

**Comment by drwpow** [comment]
Woohoo! The new version of @duetds/date-picker is out, and I was able to load it from Skypack:

<img width="1792" alt="Screen Shot 2021-02-05 at 15 15 06" src="https://user-images.githubusercontent.com/1369770/107094824-f238ed00-67c4-11eb-9699-9ee823c95e43.png">

Gonna mark this as resolved, but please let me know if you encounter any weirdness or other issues.
