### ISSUE TITLE
Main package export  "could not be built" because submodule export has node deps

### ISSUE THREAD

**Issue by manzt** [pikapkg/cdn#83]
Hi, loving Skypack CDN thanks for all the work here! I have a [pure ESM package](https://github.com/manzt/zarrita.js) that has three package exports:

-  `".": "./zarrita.js"` <-- pure ESM, no dependencies
- `"./core": "./core.js"` <-- pure ESM, no dependecies (imported by `./zarrita.js`)
- `"./fsstore": "./fsstore.js"` <-- pure ESM but node specific (imports `fs/promises` and `path`)

When I try to import in the browser from Skypack CDN, I get:

```
> import('https://cdn.skypack.dev/zarrita')
Error: [Package Error] "zarrita" could not be built.
```

Observable example comparing skypack and unpkg [here](https://observablehq.com/d/9fea94f05fd4f0f4).

I _think_ this is due to one of the package exports (`./fsstore`) having unresolved node dependencies, and skypack doing some magic to try to build all package exports on any request and cache the builds. That said, I'm surprised that I can't import `"."` or `"./core"` which have no dependencies, and I would expect this only to break if I tried to import `./fsstore` from skypack.

I'm guessing I should have a more explicit package exports to tell skypack to ignore this export, but I correct that the behavior above is unexpected?

**Comment by drwpow** [comment]
Hello! Yes it looks like `zarrita` does try and import `fs.promises` as you stated. Even though the `main` entry doesn’t import `fs`, this package is missing an [export map](https://nodejs.org/api/packages.html#packages_package_entry_points) so Skypack will try and build all JS files in the package, including the `fsstore.js` file that’s causing an issue.

The preferred way to ignore files from Skypack is providing an export map like so:

```json2
  "exports": {
    ".": "./zarrita.js", // the default entry
    "./core-96293f30.js": "./core-96293f30.js",
    "./core.js": "./core.js",
    "./fsstore.js": {
      "node": "./fsstore.js"
    }
  }
```

As indicated by the docs, [`"node"`](https://nodejs.org/api/packages.html#packages_package_entry_points) signifies that a JS file in a package is only loadable in Node, not a browser, so Skypack will ignore it.

Edit: for more clarity: `"browser"` is our recommended target and will always take priority. We will also accept `"import"` as a 2nd priority if there’s no browser, but keep in mind that `"import"` could mean ESM for Node or browser, so you may encounter the same issue. But `"node"` is meant for CommonJS or ESM _not_ loadable in browser.

Without the export map, it’s tough for Skypack to know whether or not to ignore a file for optimizing for browser. And it’s doubly hard in this scenario, where the file is modern ESM and _seems_ browser-friendly, but imports `fs.promises`.

**Comment by manzt** [comment]
Thanks for the response! 

> Even though the main entry doesn’t import fs, this package is missing an export map so Skypack will try and build all JS files in the package,

It does have an export map,https://github.com/manzt/zarrita.js/blob/main/package.json, but thanks for pointing out how this is improperly formatted / confusing for skypack. 

> Without the export map, it’s tough for Skypack to know whether or not to ignore a file for optimizing for browser. And it’s doubly hard in this scenario, where the file is modern ESM and seems browser-friendly, but imports fs.promises.

Makes total sense -- thanks for the explanation! I'll add a `"node"` key for that one export. In general, I've found it difficult to understand how various tools (e.g. skypack, bundlers, node) resolve export maps and this was very helpful.

**Comment by manzt** [comment]
hmm, @drwpow I think I'm still doing something wrong. I removed the bundler from my package, and instead now have made the `src` directory the package (https://github.com/manzt/zarrita.js/tree/main/src), but skypack is still having trouble.

https://github.com/manzt/zarrita.js/blob/cbb9539e90408793531dfc1cf45410f611d210e0/src/package.json#L15-L23

```
  "exports": {
    ".": "./zarrita.js",
    "./core": "./core.js",
    "./lib/*": "./lib/*.js",
    "./storage/httpstore": "./storage/httpstore.js",
    "./storage/fsstore": {
      "node": "./storage/fsstore.js"
    }
  },
```

**Comment by drwpow** [comment]
> In general, I've found it difficult to understand how various tools (e.g. skypack, bundlers, node) resolve export maps and this was very helpful.

Yes this is definitely a pain point for many people! It’s a new spec that’s not widely-talked about. But feel free to ask questions in here, at least as a resource.

I also forgot to call something out: currently export maps allow `./*` for “wildcard“ support, or loading entire folders. We currently **do not** support that in Skypack today but that is the very next thing on our roadmap. So if that’s not working for you today we apologize—we’re trying to support that very soon!

**Comment by drwpow** [comment]
Just an update: I’m seeing this working now on `cdn.skypack.dev/zarrita`! 🎉  Hopefully your issue is fixed but please feel free to re-open or add to this discussion if you encounter other issues.

**Comment by manzt** [comment]
Yes, all working! Thanks for all the help :)
