### ISSUE TITLE
Skypack fails on keyboard-key

### ISSUE THREAD

**Issue by DreierF** [pikapkg/cdn#85]
Hey 👋 

I was trying out Snowpack 3 with the new `experiments.source: 'skypack'` option and get the following error when I try to load the page:

https://localhost:9090/web_modules/error/build:keyboard-key@v1.1.0-GlQmbOJwUfshyv5jbVPy?from=keyboard-key
```
/*
 * [Package Error] "keyboard-key" could not be built. 
 * 
 *   Installing package...
 *   Failed to load ../../../skypack/skypack-wrap:keyboard-key/src/keyboardKey.js
 *     Unexpected token (4:16) in skypack-wrap:/tmp/cdn/_GlQmbOJwUfshyv5jbVPy/node_modules/keyboard-key/src/keyboardKey.js
 *   Install failed.
 *   Install failed.
 * 
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/pikapkg/cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://pika.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"keyboard-key\" could not be built. \nInstalling package...\nFailed to load ../../../skypack/skypack-wrap:keyboard-key/src/keyboardKey.js\n  Unexpected token (4:16) in skypack-wrap:/tmp/cdn/_GlQmbOJwUfshyv5jbVPy/node_modules/keyboard-key/src/keyboardKey.js\nInstall failed.\nInstall failed.");
throw new Error("[Package Error] \"keyboard-key\" could not be built. ");
export default null;
```

The line it complains about is [here](https://github.com/levithomason/keyboard-key/blob/master/src/keyboardKey.js#L4).

Running the same project without the flag `experiments.source: 'skypack'` works without any issues.

**Comment by drwpow** [comment]
Thanks for reporting! We’ll take a look at the issue. We’ll be making some improvements to our package builder over the coming weeks, and we’ll investigate `keyboard-key` specifically to make sure it builds.

**Comment by drwpow** [comment]
Thanks for reporting! We’ll take a look at the issue. We’ll be making some improvements to our package builder over the coming weeks, and we’ll investigate `keyboard-key` specifically to make sure it builds.

**Comment by drwpow** [comment]
Good news! With the updates to cdn.skypack.dev and Snowpack v3, this seems to be working now. Please refer to the updated docs on how to get this running with the latest version of Snowpack: https://www.snowpack.dev/guides/streaming-imports#snowpack-managed-dependencies
