### ISSUE TITLE
Deep pinning dependencies

### ISSUE THREAD

**Issue by ForbesLindesay** [pikapkg/cdn#86]
I'm trying to figure out how the following would be handled:

- I add `package-a` that depends on `react@^17.0.0` and at the time, this resolves to `react@17.0.0`. I pin (& cache) this dependency
- Later, I add `package-b` that also depends on `react@^17.0.0`, but a new version of React has been published, so the nested dependency of `package-b` is now `react@17.0.1`

How do I avoid getting two copies of React? Can I detect when this is happening. Is there a way to pin both onto the earlier react@17.0.0? Is there a way to force package-a onto the newer 17.0.1?

**Comment by drwpow** [comment]
That‘s a great question! For react this can cause issues, so we actually treat it differently than other packages on Skypack. We secretly lock React to the latest version of `17.x.x` for all packages so you‘ll never end up with multiple copies of React using Skypack.

But if React ever releases a breaking API change, we‘ll have to change our strategy a little. Fortunately that’s not on the roadmap for React, at least not as far as I know.

For nearly all other packages on Skypack, if there were hard version requirements, then yes you probably would load multiple versions of a package. Fortunately, most packages have loose version requirements so almost always only the more recent version will load. We haven‘t noticed the behavior of multiple versions of a package loading “in the wild“ yet.

**Comment by FredKSchott** [comment]
Drew's right that React is the one package that we handle special like this.

But, to your more general question: Skypack CDN guarantees that two copies of a dependency will never end up in your dependency tree as long as semver supports it. You'd modify your example above a bit to get this guarentee:

- I add `package-a` that depends on `react@^17.0.0` and at the time, this resolves to `react@17.0.0`. I pin (& cache) this dependency
- Later, I add `package-b` that also depends on `react@^17.0.0`, but a new version of React has been published, so the nested dependency of `package-b` is now `react@17.0.1`
- (New step) I regenerate all existing pinned URLs. `package-a` has a new pinned URL for me, that points to `react@17.0.1` as well.

 You can think about the hash in each pinned URL similar to a lockfile. It locks down your dependency tree to the moment it was generated. When you add a new dependency, you should update your pinned URLs like you would update your lockfile.

**Comment by ForbesLindesay** [comment]
Thanks, that makes sense. It would really help here if there was a way to use a point in time, rather than separate hashes, so that I could lock all dependencies (old & new) to only depending on versions that exist at a given point in time. Otherwise this requires me to know my exact list of dependencies up front, which negates one of the big advantages of skypack.

**Comment by FredKSchott** [comment]
Yup, right now we only support doing a full refresh of all hashes, which is analogous to clearing out your `node_modules` and lockfile and reinstalling from npm. We're interested in building out more tooling to help users accomplish this (and also keeping an eye on the "import map" spec so that you don't need to put CDN URLs all over your codebase source files.

**Comment by dbauszus-glx** [comment]
@FredKSchott ChartJS and it's plugin ecosystem is another victim of pinned dependencies. Loading plugins will cause different versions of the core library to be loaded which causes some methods to fail. https://github.com/skypackjs/skypack-cdn/issues/229

Is there an open issue in this regard since this one is closed but the problem is not resolved.
