### ISSUE TITLE
skypin & rollup-plugin-skypin

### ISSUE THREAD

**Issue by mbrandt-art** [pikapkg/cdn#87]
Hello 👋 

I've created a package [`skypin`](https://github.com/MarshallCB/skypin) and an accompanying [rollup plugin](https://github.com/MarshallCB/rollup-plugin-skypin) to generated the skypack pinned URL from a npm module id. It will manually generate the pinned URL's if they haven't been generated yet (using the method described in the skypack docs).
Example:
```js
import { lookup, skypin } from 'skypin'
// "skypin" uses version of package found in node_modules (if it exists)
await skypin('hueman')
// ~> https://cdn.skypack.dev/pin/hueman@v2.1.1-ElNqhC8YFxLlgRtjjL9o/min/hueman.js

// Or specify version directly using "lookup"
await lookup('hueman@2.0.0')
// ~> https://cdn.skypack.dev/pin/hueman@v2.0.0-Eh8v1x3dV0iEyJ9rG915/min/hueman.js
```

I've created these for a few projects I'm working on, but wanted to share in case others might want to use them! Happy to update / tweak these packages to make them more generically useful - let me know if there's anything I can do.

PS: skypack is super cool, thanks for making it great!

**Comment by drwpow** [comment]
This is really, really cool! Thanks so much for sharing. You might want to check out the `x-pinned-url` header (along with others) that are sent in a lookup request—might be easier than “RegEx shenanigans!” 😄

You actually beat us to launching our own Skypack Rollup plugin (in full disclosure, we’ve been busy working on a deep integration with Snowpack + Skypack, which [we talk about in a recent blog post](https://www.snowpack.dev/posts/2020-12-03-snowpack-3-release-candidate)).

That said, when we come back to making an official Skypack Rollup plugin, would love to talk to you to see if you’d be interested in combining work for that starting with the progress you’ve made here, or if the 2 projects may have slightly more different needs long-term and should stay separate (e.g. if you planned on baking in some custom special functionality with your Rollup plugin and wanted to maintain control over that, that’s totally cool).

**Comment by FredKSchott** [comment]
Also check out the `skypack` npm package, which is an in-progress SDK for working with Skypack URLs: https://github.com/snowpackjs/snowpack/tree/main/skypack

**Comment by FredKSchott** [comment]
Oh wait, I thought that this was just the rollup plugin! Didn't realize you'd built something similar on the sdk side as well! That's awesome!!!

**Comment by vimbrandt** [comment]
@FredKSchott @drwpow Thanks for the recommendations! I just released a new version of [`skypin`](https://github.com/MarshallCB/skypin)
- Works on browser now! [codepen](https://codepen.io/marshallcb/pen/qBaaJRY?editors=0011)
- Uses header values on the NodeJS version
- Uses content-scraping regex on browser-side to bypass headers cors issue (perhaps [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) could fix the issue on y'all's end?)
- Simpler API

**Comment by FredKSchott** [comment]
Awesome! We're just wrapping up our `?meta` support in the CDN, in case that's also helpful: https://docs.skypack.dev/skypack-cdn/api-reference/package-metadata
