### ISSUE TITLE
Import over path?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [pikapkg/cdn#9]
For example, `rxjs` main export are like this:

```
import { range } from "rxjs";
// Turns into
import { range } from "https://cdn.pika.dev/rxjs@^6.5.5";
```

But RxJS operators are under `rxjs/operators`. How can I import these files?

**Comment by FredKSchott** [comment]
Duplicate of https://github.com/pikapkg/cdn/issues/14, support is coming soon
