### ISSUE TITLE
[Skypack] [Deno] Import failed: 404 Not Found

### ISSUE THREAD

**Issue by wKovacs64** [pikapkg/cdn#97]
Hello, and thank you for your work - really cool stuff.

I maintain a library, [hibp](https://github.com/wKovacs64/hibp), and one of the dependencies, [jsSHA](https://github.com/Caligatio/jsSHA), is failing to load in Deno when importing hibp through Skypack and I was hoping you could help me figure out why. In hibp, I import a submodule of jsSHA like so:

```ts
import JSSHA from 'jssha/dist/sha1'
```

But when I import hibp in a Deno app via Skypack, I get the following:

```
Download https://cdn.skypack.dev/hibp@10.0.1
Download https://cdn.skypack.dev/-/hibp@v10.0.1-0ohsxSpRsakKdNl03fu0/dist=es2020/hibp.js
Download https://cdn.skypack.dev/-/isomorphic-unfetch@v3.1.0-KKyJFmycHb9q8N8SVFDo/dist=es2020/isomorphic-unfetch.js
Download https://cdn.skypack.dev/-/jssha@v3.2.0-7ih4rHNyCNAz1Lqwkzy4/dist=es2020/jssha/dist/sha1
Download https://cdn.skypack.dev/-/unfetch@v4.2.0-C1IyXUnfqIHy5HNGftHY/dist=es2020/unfetch.js
error: Import 'https://cdn.skypack.dev/-/jssha@v3.2.0-7ih4rHNyCNAz1Lqwkzy4/dist=es2020/jssha/dist/sha1' failed: 404 Not Found
    at https://cdn.skypack.dev/-/hibp@v10.0.1-0ohsxSpRsakKdNl03fu0/dist=es2020/hibp.js:2:0
```

If you hit the offending URL directly, it results in the following:

```
File "exports/jssha/dist/sha1" not found.
```

Both jsSHA ([package.json](https://github.com/Caligatio/jsSHA/blob/7e1453e8ce7ef75df44da605102bec92a274b333/package.json#L15) | [dist](https://unpkg.com/browse/jssha@3.2.0/dist/)) and hibp ([package.json](https://github.com/wKovacs64/hibp/blob/5505b1175a1380b1c2377c66a3dcbdecd738e00e/package.json#L28) | [dist](https://unpkg.com/browse/hibp@10.0.1/dist/)) have an `exports` map and the published output is as I'd expect, for whatever that's worth. Not sure where to go from here with regards to troubleshooting.

Thanks!

**Comment by wKovacs64** [comment]
This may be able to be reduced down to:

Works (without `dist`):

```
import jssha from "https://cdn.skypack.dev/jssha/sha1";
```

Doesn't work (with `dist`):

```
import jssha from "https://cdn.skypack.dev/jssha/dist/sha1";
```

And whether or not we can/should do something in jsSHA to address that? 🤔

**Comment by drwpow** [comment]
Update: we recently pushed an update to the CDN which seems to resolve this! I’m able to `import hipb from "https://cdn.skypack.dev/hibp@10.0.1?dts"` in Deno and it seems to import propertly. However I haven’t tried building an app using this, so please let us know if you encounter any other issues in Deno (ideally as a new ticket to help keep track of it).

**Comment by wKovacs64** [comment]
You fixed it! 😃 Confirmed locally that it's working as expected. Thank you!
